<?php $max_files = Zend_Controller_Front::getInstance()->getRequest()->getParam('max', 5); ?>

<?php
$vendorIdSegment = !empty($this->vendor_id) ? '/vendor_id/'.$this->vendor_id : '';
$submissionHashSegment = '/submission_hash/'.$this->submission_hash;
?>

<form class="form" method="post"
	action="<?php echo $this->baseUrl('vendor/royalty/upload-report'.$vendorIdSegment.$submissionHashSegment) ?>"
	id="upload-report-form">
	<div id="uploader">
		<p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or
			HTML5 support.</p>
	</div>
	<div class="form_default">
		<div class="four_fifth">
			<?php
			echo $this->formHidden("upload_file_name", "");
			echo $this->formSubmit('Submit', 'Submit', array('class' => 'button button_brown'));
			?>
		</div>
	</div>
	<div class="clear"></div>
	</div>
</form>
<script type="text/javascript">
	
			
    $(function() {
	var files = [];

	console.log(site_url + '/admin/license/upload');
	
	//var is_submitted = false;
        $("#uploader").pluploadQueue({
            runtimes : 'html5,gears,silverlight,flash,html4',
            url : site_url+'/admin/license/upload',
            max_file_size : '20mb',
            max_file_count: '1', // user can add no more then 20 files at a time
            chunk_size : '1mb',
            unique_names : true,
	    	prevent_duplicates: true,
            multiple_queues : true,
            resize : {width : 1024, height : 768, quality : 90},
            rename: true,
            sortable: true,
            filters : [
                {title : "Image files", extensions : "pdf,xls,xlsx,doc,docx,jpg, jpeg,png"}
            ],
            'flash_swf_url' : site_url+"/assets/js/plupload/plupload.flash.swf",
            'silverlight_xap_url' : site_url+"/assets/js/plupload/plupload.silverlight.xap",
            init : {
                FileUploaded: function(up, file, info) {
                    if(info.status==200){
						files.push(file.target_name);
                        $("#upload_file_name").val(files.join(','));
                    }else{
                        alert('Problem occurred in uploading')
                    }
                },
                UploadFile : function(up,file) {

                }
            }
        });

        // Client side form validation
        $('form').submit(function(e) {

            var uploader = $('#uploader').pluploadQueue();

            if (uploader.files.length > 0) {

            	console.log('starting');
    			uploader.bind('StateChanged', function() {
		    		if (uploader.files.length == (uploader.total.uploaded + uploader.total.failed)) {
			    		console.log('submitting');
					    ajax_submit_report();
					}
				});
               
                uploader.start();
                
            } else {
                alert('You must queue at least one file.');
            }
            return false;
        });
    });

    function ajax_submit_report(){
        $.ajax({
            url : site_url+"/admin/vendors/ajax-save-agreement/vendor_id/<?php echo $this->vendor_id; ?>/license_number/<?php echo $this->license_number?>",
            data : $('#upload-report-form').serialize(),
            type : 'post',
            dataType : 'json',
            success : function(e){
				console.log('success');
                
                if(e.code=="success"){
		            window.parent.close_upload_dialog();
                }
            },
            error: function(e){
				console.log('error');
				console.log(e);
            }
        });
    }
</script>
<br />
<style type="text/css">
* {
	font: 13px arial, helvetica;
}
</style>
