<div>       
    <b><?php echo 'Q' . $this->report->quarter; ?></b> Quarterly Report Detail Submitted on <b><?php echo $this->report->uploaded_on->format('M d, Y'); ?></b> <br /><br />
    <?php if(sizeof($this->reports)) : ?>     
    <table cellpadding="0" cellspacing="0" border="0" class="sTable2" width="100%">
        <thead>
            <tr role="row">
                <th align="left" width="25%">Greek Org.</th>
                <?php if($this->vendor_reporting_type == 1) {?>
                	<th align="left" width="15%">Gross Sales</th>
                <?php } elseif($this->vendor_reporting_type == 2) {?>
                	<th align="left" width="15%">Units Sold</th>
                <?php } elseif($this->vendor_reporting_type == 3) {?>
                	
                <?php }?>
                <?php if(in_array($this->vendor_reporting_type, array(1,2))) {?>
                	<th aling="left" width="15%">Royalty <br/>(<?php echo $this->vendor_reporting_type == 2 ? '$' : '%'?>)</th>
                <?php }?>
                <th align="left" width="15%">Royalty Due</th>                
            </tr>
        </thead>
        <tbody>                    
            <?php $total = 0; ?>
            <?php foreach ($this->reports as $r): ?>   
                <tr>
                    <td width="25%"><?php echo $r->client->organization_name ?></td>
                    
                    <?php if($this->vendor_reporting_type == 1) {?>
	                	<td width="15%"><?php echo $this->BUtils()->getCurrency($r->gross_sales)?></td>
	                <?php } elseif($this->vendor_reporting_type == 2) {?>
	                	<td width="15%"><?php echo $r->quantity?></td>
	                <?php } elseif($this->vendor_reporting_type == 3) {?>
                	
                	<?php }?>
                    <?php if(in_array($this->vendor_reporting_type, array(1,2))) {?>
                    <td width="15%"><?php echo is_null($r->royalty_commission) ? 'N/A' : $r->royalty_commission ?></td>
                    <?php }?>
                    <td width="15%"><?php echo $this->BUtils()->getCurrency($r->royalty_after_adv); ?></td>                    
                </tr>                                          
            <?php $total += $r->royalty_after_adv; ?>    
            <?php endforeach; ?>
            <tr>
                <?php if($this->vendor_reporting_type != 3) {?>
                	<td width="15%">&nbsp;</td>
                <?php }?>
                <?php if(in_array($this->vendor_reporting_type, array(1,2))) {?>
                	<td width="15%">&nbsp;</td>
                <?php }?>
                <td width="15%" class="total_row">Total</td>
                <td width="15%" class="total_col"><?php echo $this->BUtils()->getCurrency($total); ?></td>
            </tr>
        </tbody>
    </table>  
    <?php endif; ?>
</div>

<style type="text/css">
    .total_txt{font-weight: bold; text-align: right;}
    .total_amt{font-weight: bold;}
</style>