<div class="spacer"></div>
<hr size="1" noshade />
<div class="spacer"></div>
<div class="one padding15">
    <p>Select the file with your quarterly sales information. The file format can be MS Word, Excel, PDF, JPG, JPEG.</p>
</div>
<div class="clear"></div>

<div class="spacer clear"></div>

<style type="text/css">
    p{font-size: 130%}
    span.revenue{font-size: 115%}
    span.green{color:green;}
    span.red{color:red;}
</style>

           
