<h1>Background Jobs</h1>
<br />
<table cellpadding="0" cellspacing="0" border="0" class="dyntable sTable2" id="licenses-data-table">
    <thead>
        <tr>
            <th class="head0">Process ID</th>
            <th class="head1">Status</th>
            <th class="head0">Function</th>
            <th class="head1">Percent Done</th>
            <th class="head0">Started</th>
            <th class="head1">Action</th>
        </tr>            
    </thead>
    <tbody>
        <?php foreach($this->pending_jobs as $job): ?>
        <tr>
            <td><?php echo $job->process_id; ?></td>
            <td><?php echo $job->status; ?></td>
            <td><?php echo $job->function_name; ?></td>
            <td><?php echo $job->percent_done; ?></td>
            <td><?php echo $job->process_started->format("M d, Y H:i:s"); ?></td>
            <td><a href="<?php echo $this->baseUrl("admin/jobs/terminate/id/".$job->id); ?>">Terminate</a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>