<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('layout/sidebar-calendar.phtml');
$this->placeholder('main_side_bar')->captureEnd();

$this->placeholder('sub_menu_bar')->captureStart();
echo $this->partial('artworks/sub-menu-bar.phtml', array('selected'=>'usage-guides'));
$this->placeholder('sub_menu_bar')->captureEnd();
?>
<div id="view-content">
    <div class="one"><h2>Add Usage Guide</h2></div>
    <div class="spacer clear"></div>
    <form  action="" method="POST" enctype="multipart/form-data" id="<?php echo $this->form->getName(); ?>">        
        <div class="one"><?php echo $this->form->guide_name; ?></div>
        <div class="spacer clear"></div>

        <div class="one"><?php echo $this->form->guide_document; ?></div>
        <div class="spacer clear"></div>

        <div class="one"><?php echo $this->form->guide_content; ?></div>
        <div class="one" id="msg_error"></div>
        <div class="spacer clear"></div>

        <div class="one"><button type="submit" id="submit_button" class="button button_blue" >Submit</button></div>
        <div class="spacer clear"></div>
    </form>
</div>
<script type="text/javascript">
    tinyMCE.init({
        mode : "textareas",
        elements : "guide_content",
        theme : "advanced",
        height: "300",
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor,hr,removeformat,visualaid,|,sub,sup,|,charmap",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_path : false,
        theme_advanced_font_sizes: "8px, 9px, 10px, 11px, 12px,14px,16px,18px,20px,24px,28px,36px,44px",
        font_size_style_values : "13px, 14px,16px,18px,20px",
        content_css : "<?php echo $this->baseUrl("assets"); ?>/css/custom_content.css",
        force_br_newlines : true,
        force_p_newlines : false,
        forced_root_block : "",
        theme_advanced_resizing : true,
        skin : "o2k7",
        skin_variant : "silver"
    });
</script>
<script type="text/javascript">       
    $(function(){                                 
        $('#usageguide_form').validate({
            errorClass : 'error',
            rules:{
                guide_name : {'required' : true},
                           
            },
            messages:{
                guide_name : {'required' : "<br />Please enter guide name"},
                              
            },
            submitHandler:function(form){
                form.submit();
            }
        })
    });
</script>

