<h2>Edit usage guide</h2>
<hr size="1" noshade />
<div class="spacer clear"></div>

<form action="" enctype="multipart/form-data" method="POST" id="<?php echo $this->form->getName(); ?>">
    <div class="one" style="font-size: 12px; font-weight: normal;">
         <?php echo $this->form->guide_name; ?>
    </div>
    <div class="one" style="display: none;"><?php echo $this->form->guide_document; ?></div>
    <div class="spacer clear"></div>
    
    <div class="one" style="font-size: 12px; font-weight: normal;">
        <?php echo $this->form->guide_content;?>
    </div>
    <div class="spacer clear"></div>
    <div class="one">
        <button type="submit" class="button button_black" >Submit</button>
    </div>
</form>

<style type="text/css">
    form{margin: 0px; padding: 0px;}
</style>

<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
 $(document).ready( function($) {    
    if(('<?php echo $this->msg; ?>') !=""){      
        window.parent.execute_refresh('<?php echo $this->msg; ?>');
    }    
 });
</script>
<script type="text/javascript">
    tinyMCE.init({
        mode : "textareas",
        elements : "guide_content",
        theme : "advanced",
        height: "300",
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor,hr,removeformat,visualaid,|,sub,sup,|,charmap",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_path : false,
        theme_advanced_font_sizes: "8px, 9px, 10px, 11px, 12px,14px,16px,18px,20px,24px,28px,36px,44px",
        font_size_style_values : "13px, 14px,16px,18px,20px",
        content_css : "<?php echo $this->baseUrl("assets"); ?>/css/custom_content.css",
        force_br_newlines : true,
        force_p_newlines : false,
        forced_root_block : "",
        theme_advanced_resizing : true,
        skin : "o2k7",
        skin_variant : "silver"
    });
</script>
<script type="text/javascript">
    validated=false;
    $(function(){
        $("#usageguide_form").on('submit',function(){
            $form=$(this);
            if(!validated){
                $.ajax({
                    type: 'post',
                    data : $("#usageguide_form").serialize(),
                    dataType: 'json',
                    success: function(e){
                        $valid=$.isEmptyObject(e) ? true : false;
                        if(!$valid){
                            $form.find('.error').removeClass('error');
                            $form.find('.js_gen_errors').remove();
                            for(var i in e){
                                $.map( e[i], function(val, k) {
                                    $('input[name='+i+']').addClass('error')
                                    .after('<ul class="errors js_gen_errors"><li>'+val+'</li></ul>');
                                });
                            }
                            return false;
                        }else{
                            validated=true;
                            $form.find('.error').removeClass('error');
                            $form.find('.js_gen_errors').remove();
                            $form[0].submit();
                            return true;
                        }
                    }
                });
                return false;
            }
        })
    });
</script>

