<ul class="submenu">
    <li<?php echo $this->selected == "index" ? ' class="current"' : ''; ?>><a href="<?php echo $this->url(array('controller' => 'artworks', 'action' => 'index'));?>"><span>Artwork</span></a></li>
    <li<?php echo $this->selected == "usage-guides" ? ' class="current"' : ''; ?>><a href="<?php echo $this->url(array('controller' => 'artworks', 'action' => 'usage-guides')); ?>"><span>Usage Guides</span></a></li>    
</ul>