<?php 
$user = Zend_Auth::getInstance()->getIdentity();
?>
<ul class="leftmenu">
    <li><a href="javascript:;" class="file">Contact</a></li>
    <li><a href="javascript:;" class="file">Correspondence</a></li>
    <li><a href="javascript:;" class="file">Operations</a></li>
    <li><a href="javascript:;" class="file">Clients</a></li>
    <li><a href="javascript:;" class="file">Lisc. Agreements</a></li>
    <li><a href="javascript:;" class="file">Action</a></li>
    <?php if ($user->account_type == 1){?><li><a href="javascript:;" class="file">Payments</a></li><?php }?>
    <li><a href="javascript:;" class="file">Notes</a></li>
    <li><a href="javascript:;" class="file">Docs</a></li>
    <li><a href="javascript:;" class="file">Invoices</a></li>
    <li><a href="javascript:;" class="file">Designs</a></li>
    <li><a href="javascript:;" class="file">Product Samples</a></li>
</ul>
