## Status Description.
---
All : All
Annual : Annual
Monthly : Monthly
First Time Advance : First Time Advance
Misc. : Misc.
Late Fee : Late Fee
One-Time : One-Time
Quarterly Report : Quarterly Report
Ads : Ads
Refund : Refund
Royalty Payments : Royalty Payments
