<ul class="leftmenu">
<!--    <li><a href="javascript:;" class="file">Organization Info</a></li>
    <li><a href="javascript:;" class="file">Web Profile</a></li>-->
    
    
    <li<?php echo $this->selected=='license' ? ' class="current"' :  ''; ?>><a href="<?php echo $this->baseUrl("client/license/"); ?>" class="file">Back To All Licenses</a></li>

<!--     <li<?php echo $this->selected=='artworks' ? ' class="current"' :  ''; ?>><a href="<?php echo $this->baseUrl("client/artworks/"); ?>" class="file">Artworks</a></li> -->

</ul>