<ul class="submenu">
    <li<?php echo $this->selected == "index" ? ' class="current"' : ''; ?>><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'contact'));?>"><span>Organization Info</span></a></li>
    <li<?php echo $this->selected == "web-profile" ? ' class="current"' : ''; ?>><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'web-profile')); ?>"><span>Web Profile</span></a></li>    
</ul>