<?php if ($this->pageCount > 1): ?>
    <div class="pagination_total">Showing <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> of <?php echo $this->totalItemCount; ?> Records </div>
    <div class="pagination pgleft">

        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => $this->first)); ?>" class="first" > « First </a>
        <?php else: ?>
            <a class="first disabled">« First</a> 
        <?php endif; ?>

        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" class="prev" > &laquo; ‹ Prev </a>
        <?php else: ?>
            <a class="prev disabled">‹ Prev</a> 
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"> <?php echo $page; ?> </a>
            <?php else: ?>
                <a href="javascript:;" class="current"><?php echo $page; ?></a>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>" class="next" > Next › &raquo; </a>
        <?php else: ?>
            <a class="next disabled">Next ›</a>
         <?php endif; ?>
        
         <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url(array('page' => $this->last)); ?>" class="last" > Last » </a>
        <?php else: ?>
            <a class="last disabled"> Last » </a>
         <?php endif; ?>
    </div>
<?php endif; ?>
