<!--Dear <?php //echo $this->username; ?>, <br /><br />
 
Thank you for registering with Greek Licensing. We will review the information you have submitted and get back to you within 1 business day.<br /><br />
 
Please reply to this email should you have any questions in the meantime.<br /><br /><br />
 
Regards, <br /><br />
 
Melissa Jean-Baptiste<br />
Licensing Department<br />
e: Registration@greeklicensing.com<br />
p: 760-734-6764 ext. 140<br />
f:  707-202-0532 <br />-->

Dear <?php echo $this->organization_name; ?>, <br /><br />

Please follow <a href="http://centos.softura.com/crm/signup/existing-user-key">this link</a> to continue creating your username and password.<br /><br />

<b>Activation Key:</b> <?php echo $this->key;?><br /><br />

If you have any questions, please feel free to contact us.<br /><br /><br />
 
Licensing Department<br />
e: Registration@greeklicensing.com<br />
p: 760-734-6764 ext. 140<br />
f:  707-202-0532 <br />