Dear <?php echo $this->user->organization_name; ?>: <br />


Someone, probably you made a password reset request at GreekLicensing.com. <br />

We have reset your password to the following : <br /><br />

New Password : <?php echo $this->new_password; ?>


<br /><br />

Regards, <br /><br />
 
Melissa Jean-Baptiste<br />
Licensing Department<br />
e: Registration@greeklicensing.com<br />
p: 760-734-6764 ext. 140<br />
f:  707-202-0532 <br />
