<!--Dear <?php //echo $this->username; ?>, <br /><br />
 
Thank you for registering with Greek Licensing. We will review the information you have submitted and get back to you within 1 business day.<br /><br />
 
Please reply to this email should you have any questions in the meantime.<br /><br /><br />
 
Regards, <br /><br />
 
Melissa Jean-Baptiste<br />
Licensing Department<br />
e: Registration@greeklicensing.com<br />
p: 760-734-6764 ext. 140<br />
f:  707-202-0532 <br />-->

Dear <?php echo $this->organization_name; ?>, <br /><br />
 
Thank you for requesting access to the Vendor Gateway with the username: <b><?php echo $this->username; ?></b>. Before granting you access we must review and confirm the information you have submitted. We will send an additional follow up email once this review is complete.<br /><br />
 
If you have any questions in the meantime, please feel free to contact us.<br /><br /><br />
 
Licensing Department<br />
e: Registration@greeklicensing.com<br />
p: 760-734-6764 ext. 140<br />
f:  707-202-0532 <br />