<?php echo $this->doctype() ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php //echo $this->me->roles->role_name;?>
        <link rel="shortcut icon" href="/favicon.ico" />


        <!-- <link rel="stylesheet" type="text/css" media="screen" href="/css/960_12_10_10.css" /> -->
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/960_12_fluid.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/reset.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/text.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/styles.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/ui_themes/pepper-grinder/jquery-ui-1.8.6.custom.css" />

    </head>

    <body>
        <!-- header -->
        <div class="wrapper">
            <div class="topbg">
                <div class="container_12">
                    <div class="grid_12 alpha omega" style="padding-bottom:30px; padding-top:10px">
                        <div class="grid_5 alpha omega">
                            <a href="#"> <img src="<?php echo $this->baseUrl("assets/images/logo.png") ?>" alt="logo" title="logo" />
                            </a>
                        </div>
                        <div class="grid_4 omega" style="float:right; text-align:right">
                            <?php //include_partial('global/user') ?>
                            <?php
                            if (Zend_Auth::getInstance()->hasIdentity()) {
                                $auth_usr = Zend_Auth::getInstance()->getIdentity();
                            ?>
                                Hi, <?php echo isset($auth_usr->first_name) ? $auth_usr->first_name : "Guest" ?>
                            <?php } ?>
                            <?php if (!Zend_Auth::getInstance()->hasIdentity()) {
 ?>
                                
<?php } else { ?>
                                &nbsp;&nbsp;|&nbsp;&nbsp;
                                <a href="<?php echo $this->baseUrl("login/logout"); ?>">Logout</a>
<?php } ?>
                        </div>

                        <div class="grid_3">
                            <span class="sitetitle">

<!--                           Greek Licensing <?php //echo ucfirst($sf_user->getGroups()->getFirst()->getName())     ?> Portal-->

<?php if(isset($auth_usr->account_type)){
    echo "Greek Licensing ". $auth_usr->roles->role_name ." Portal" ;
}
else{
    echo "Greek Licensing Portal" ;
}
?>

                            </span>
                        </div>


                    </div>
                    <div class="clear">&nbsp;</div>


                    <!-- notification -->
                    <div id="notification">

<?php //include_component_slot('notification')  ?>

                        </div>
                        <!-- notification ends -->


                        <!-- header end-->
                        <!-- body -->




                        <!-- content -->
                        <!--                            <div class="grid_12 ">-->



<?php echo $this->layout()->content ?>



                            <!--                            </div>-->
                            <!-- content end -->



                            <!-- side bar -->

                            <!-- This component slot depends on view.yml configuration; look for which
                            module and component its passing as a parameter -->
<?php //include_component_slot('calendar')  ?>

                    <!-- side bar ends -->
                    <!-- body end -->
                </div>


            </div>

            <div class="clear">&nbsp;</div>

            <!-- footer -->
            <div class="footer_wrapper">
                <div class="container_12">

                    <div class="grid_12 footer">

                        Greek Licensing Portal

                    </div>

                </div>
            </div>
            <!-- footer end -->
        </div>

    </body>
</html>


