<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/style.css" />                
        <script type="text/javascript">var site_url="<?php echo $this->baseUrl(); ?>";</script>        
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/jquery/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/plugins/jquery-ui-1.8.16.custom.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/plugins/jquery.jgrowl.js"></script>
        <?php echo $this->headScript(); ?>
    </head>
    <body class="bodywhite">        
<!--        <div class="maincontent">-->
            <?php echo $this->layout()->content; ?>
<!--        </div>-->
    </body>
</html>