<h3>Email Invoice</h3>
<hr size="1" noshade />

<p style="font-weight: bold;">Please verify that the following information is correct before you send out the invoice.</p>

<form name="email_invoice_form" id="email_invoice_form" action="" method="POST">
    <div class="one">
        <div class="left_div">
            <?php echo $this->form->from_name; ?>
            <div class="clear"></div>
            <?php echo $this->form->from_email; ?>            
        </div>
        <div class="right_div">
            <?php echo $this->form->to_name; ?>
            <div class="clear"></div>
            <?php echo $this->form->to_email; ?>            
        </div>        
        <div class="clear"></div>

        <?php echo $this->form->cc_email; ?>
        <div class="clear"></div>
        <?php echo $this->form->subject; ?>
        <div class="clear"></div>
        <?php echo $this->form->email_body; ?>        
        <div class="clear"></div>

        <button name="cancel" id="cancel" type="button" class="button button_black">Cancel</button>&nbsp;
        <button name="send_invoice" id="send_invoice" type="submit" class="button button_black">Send Invoice</button>&nbsp;        
    </div>
</form>


<style type="text/css">
    form{padding: 0px; margin: 0px;}
    #from_name,#from_email,#to_name,#to_email{width: 275px; height: 18px;}
    #cc_email,#subject{width:600px; height: 18px;}
</style>

<script type="text/javascript">
    $(window).bind('load', function(){
        email_functions.init_email_message();
        email_functions.init_tiny_mce();
        $(document).on('click', 'button#cancel', email_functions.close_popup_form);
    });
    
    email_functions={        
        init_email_message : function(){
            if('<?php echo $this->result['success']; ?>'){
                window.parent.execute_refresh('<?php echo $this->result['message']; ?>');
            }  
        },  
        init_tiny_mce : function(){
            tinyMCE.init({
                mode : "textareas",
                elements : "email_body",
                theme : "advanced",
                height: "250",
                theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
                theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor,hr,removeformat,visualaid,|,sub,sup,|,charmap",
                theme_advanced_buttons3 : "",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                theme_advanced_statusbar_location : "bottom",
                theme_advanced_path : false,
                theme_advanced_font_sizes: "8px, 9px, 10px, 11px, 12px,14px,16px,18px,20px,24px,28px,36px,44px",
                font_size_style_values : "13px, 14px,16px,18px,20px",
                content_css : "<?php echo $this->baseUrl("assets"); ?>/css/custom_content.css",
                force_br_newlines : true,
                force_p_newlines : false,
                forced_root_block : "",
                theme_advanced_resizing : true,
                skin : "o2k7",
                skin_variant : "silver"
            });  
        },
        close_popup_form : function(){
            window.parent.close_popup();
        }        
    }
            
</script>