Dear <?php echo $this->username; ?>, <br /><br />

An invoice from Affinity Consultants has been generated and is ready for payment.  <br /><br />

The details of the invoice are below: <br /><br />

<?php echo $this->invoice_template; ?>

<br />

Please log into your account by going to <a href="http://www.greeklicensing.com">www.greeklicensing.com/login</a> and click on the Invoices tab in order to view details and submit payment.

Thank You, <br />

Accounting Department<br />
e: accounting@greeklicensing.com<br />
p: 760-734-6764 ext. 140<br />
f: 707-202-0532 <br />