<div>
    <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td width="50%" align="left">
                <table width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td width="35%" align="left"><b>Vendor Name</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->company_name; ?></td>
                    </tr>
                    <tr>
                        <td width="35%" align="left"><b>Invoice Type</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->invoice_type; ?></td>
                    </tr>               
                    <tr>
                        <td width="35%" align="left"><b>Invoice Term</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->invoice_term; ?></td>
                    </tr>               
                    <tr>
                        <td width="35%" align="left"><b>Address</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->address_line1; ?></td>
                    </tr>    
                    <tr>
                        <td width="35%" align="left">&nbsp;</td>
                        <td width="5%" align="left">&nbsp;</td>
                        <td width="60%" align="left"><?php  echo $this->invoice->address_line2; ?></td>
                    </tr>  
                    <tr>
                        <td width="100%" colspan="3" align="left" ><b>City : </b><?php  echo $this->invoice->city; ?>&nbsp;&nbsp;<b>State : </b> <?php  echo $this->invoice->state; ?>&nbsp;&nbsp;<b>Zip : </b> <?php  echo $this->invoice->zip; ?></td>                        
                    </tr> 
                </table>                                
            </td>
            <td width="50%" align="left">
                <table width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td width="35%" align="left"><b>Invoice Number</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->invoice_number; ?></td>
                    </tr>
                    <tr>
                        <td width="35%" align="left"><b>Invoice Date</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->invoice_date->format('m/d/Y'); ?></td>
                    </tr> 
                    <tr>
                        <td width="35%" align="left"><b>Email</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->email; ?></td>
                    </tr>               
                    <tr>
                        <td width="35%" align="left"><b>Phone</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->phone1; ?></td>
                    </tr>    
                    <tr>
                        <td width="35%" align="left">&nbsp;</td>
                        <td width="5%" align="left">&nbsp;</td>
                        <td width="60%" align="left"><?php  echo $this->invoice->phone2; ?></td>
                    </tr>   
                    <tr>
                        <td width="35%" align="left"><b>Fax</b></td>
                        <td width="5%" align="left"><b>:</b></td>
                        <td width="60%" align="left"><?php  echo $this->invoice->fax; ?></td>
                    </tr> 
                </table>                    
            </td>
        </tr>            
        <tr><td colspan="2">&nbsp;</td></tr>
    </table>    
    <?php if(sizeof($this->lineitems)) : ?>
    <?php
    $quarters = array(0 => 'N/A', 1 => 'First', 2 => 'Second', 3 => 'Third', 4 => 'Fourth');
    $alt = true;
    $currency = new Zend_Currency('en_US');
    ?>    
    <table cellpadding="0" cellspacing="0" border="0" width="100%">
        <thead>
            <tr role="row">
                <th width="10%" align="left"><b>Line Item#</b></th>
                <th width="20%" align="left"><b>Organization</b></th>
                <th width="10%" align="left"><b>Year</b></th>
                <th width="10%" align="left"><b>Quarter</b></th>
                <th width="10%" align="left"><b>Date</b></th>
                <th width="12%" align="left"><b>Check#</b></th>
                <th width="14%" align="left"><b>Amount Due</b></th>
                <th width="14%" align="left"><b>Amount Paid</b></th>
            </tr>
        </thead>
        <tbody>
            <?php $i = $total_due = $total_paid = 0; ?>
            <?php foreach ($this->lineitems as $item): ?>
            <?php $i++; $total_due += $item->amount_due; $total_paid += $item->amount_paid; ?>
                <tr class="<?php echo ($alt = !$alt) ? "odd" : "even"; ?>">
                    <td width="10%"><?php echo $i; ?></td>
                    <td width="20%"><?php echo $item->client_id->organization_name; ?></td>
                    <td width="10%"><?php echo isset($item->fiscal_year) ? $item->fiscal_year : 'N/A'; ?></td>
                    <td width="10%"><?php echo $quarters[$item->quarter]; ?></td>
                    <td width="10%"><?php echo ( (int) $item->created_at->format("Y") > 0 ? $item->created_at->format("m/d/Y") : 'N/A'); ?></td>                    
                    <td width="12%"><?php echo isset ($item->check_number) ? $item->check_number : 'N/A'; ?></td>
                    <td width="14%"><?php echo $currency->toCurrency($item->amount_due); ?></td>
                    <td width="14%"><?php echo $currency->toCurrency($item->amount_paid); ?></td>
                </tr>
            <?php endforeach; ?>                
                <tr>
                    <td width="10%">&nbsp;</td>
                    <td width="20%">&nbsp;</td>
                    <td width="10%">&nbsp;</td>
                    <td width="10%">&nbsp;</td>
                    <td width="10%">&nbsp;</td>                    
                    <td width="12%" class="total_txt">Total&nbsp;&nbsp;</td>
                    <td width="14%" class="total_amt"><?php echo $currency->toCurrency($total_due); ?></td>
                    <td width="14%" class="total_amt"><?php echo $currency->toCurrency($total_paid); ?></td>
                </tr>
        </tbody>
    </table>
<?php endif; ?>
</div>

<style type="text/css">
    .total_txt{font-weight: bold; text-align: right;}
    .total_amt{font-weight: bold;}
</style>