<h3>Mark as paid</h3>
<hr size="1" noshade />

<div class="one">
    <form name="mark_as_paid" id="mark_as_paid_id" action="" method="POST">
        Invoice Total: &nbsp;<b><?php echo $this->BUtils()->getCurrency($this->total_due); ?></b>                                
        <div class="spacer clear"></div>
        <?php echo $this->form->payment_type; ?>
        <div class="clear"></div>
        <?php echo $this->form->payment_ref; ?>
        <div class="clear"></div>
        <?php echo $this->form->payment_amount; ?>
        <div class="clear"></div>
        <?php echo $this->form->payment_date; ?>
        <input type="hidden" name="invoice" id="invoice" value="<?php echo $this->invoice->id; ?>" />
        <input type="hidden" name="vendor" id="vendor" value="<?php echo $this->invoice->vendor_id->id; ?>" />
        <div class="spacer clear"></div>
        
        <div class="floatleft">
            <button name="cancel" id="cancel" type="button" class="button button_black">Cancel</button>&nbsp;
            <button name="record_payment" id="record_payment" type="button" class="button button_black">Record Payment</button>&nbsp;
        </div>
        <div class="floatleft" id="wait" style="display: none;">
            <img src="<?php echo $this->baseUrl('assets/images/loading.gif'); ?>" style="margin: 10px 10px;" />
        </div>
    </form>
</div>

<style type="text/css">
    form{padding: 0px; margin: 0px;}
    .text{width: 95%; text-align: center;}
    .select{width: 100%;}
</style>


<script type="text/javascript">
    $(window).bind('load', function(){
        event_functions._initialize();
        $(document).on('click', 'button#cancel', event_functions.close_popup_form)
        $(document).on('click', 'button#record_payment', event_functions.record_payment);
    });
    
    event_functions = {
        _initialize : function(){
            
        },
        record_payment : function(){
         //   $.ajax({
          //      url: site_url+'/admin/invoice/mark-As-Paid/id/'+$("input#vendor").val()+'/inv_id/'+$("input#invoice").val(),
           //     type: "POST",    
            //    dataType: 'json',
             //   data:$('#mark_as_paid_id').serialize(),
              //  beforeSend: function() {                             
               //     $('#wait').show();
               // },
                //complete: function() {                             
                //    $('#wait').hide();
                //},
                //success: function(response) { 
//                    console.log(response);         
                  //  window.parent.execute_refresh(response.message); 
                //}
           // });
			
           // var data = $('#mark_as_paid_id').serialize();

            $.ajax({
                url: site_url + '/admin/invoice/ajax-set-review-data/id/'+$("input#vendor").val()+'/inv_id/'+$("input#invoice").val(),
            	type: "POST",
            	dataType: 'json',
            	data:$('#mark_as_paid_id').serialize(),
            	success: function(response){
						console.log("yada");

						window.parent.location.href = site_url + '/admin/invoice/invoice-payment-review/id/' + $("input#vendor").val() + '/inv_id/' + $("input#invoice").val()+'/mark-as/paid';
                	}
            });
        },
        close_popup_form : function(){
            window.parent.close_popup();
        }   
    }    
</script>