<?php
//print_r($this->imageLink);
//echo $this->baseUrl('assets/files/samples/products/'. $this->imageLin)
?>

<!--<h3>Product Sample</h3>
<hr/>-->
<div id="product_sample_image" style='float:left; width: 100%; height: 100%; padding-left:5px;'>
    <img src="<?php echo $this->baseUrl('assets/files/samples/products/large/'. $this->imageLink)?>">
</div>
<!--<div id="sample_image_download">
    <a href="<?php //echo $this->baseUrl('assets/files/samples/products/'. $this->imageLink)?>">Download Image</a>
</div>-->
