<ul class="submenu">
    <li<?php echo $current_controller == "contact" ? ' class="current"' : ''; ?>><a href="javascript:;"><span>Contact</span></a></li>
    <li<?php echo $current_controller == "index" ? ' class="current"' : ''; ?>><a href="<?php echo $this->baseUrl("vendor/index/edit"); ?>"><span>Web Profiles</span></a></li>
    <li<?php echo $current_controller == "license" ? ' class="current"' : '' ?>><a href="javascript:;"><span>Lisc. Agreements</span></a></li>
    <li<?php echo $current_controller == "events" ? ' class="current"' : ''; ?>><a href="javascript:;"><span>Events</span></a></li>
    <li<?php echo $current_controller == "notifications" ? ' class="current"' : ''; ?>><a href="javascript:;"><span>Notifications</span></a></li>
    <li<?php echo $current_controller == "website" ? ' class="current"' : ''; ?>><a href="javascript:;"><span>Website Management</span></a></li>
</ul><!--submenu-->