<?php $mainPages='all';
//print_r($this->event_title);
//$events = $this->events;
$this->headTitle('Events');
?>
  <div id="view-content">
    <div  class="one_fourth">
        <div id="wait1">
            Loading...
        </div>
    </div>
    <div class="clear"></div>
    <div class="">
        <h1 class="pageTitle">Events Page</h1>
        <a class="addNewButton" href="<?php echo $this->baseUrl()?>/admin/event/add">+Add New Event</a>
        <ul class="submenu" id="page_select" style="border:0 none; padding: 0px;">
            <li class="current" id="all"><a rel="all" href="javascript:;">All</a></li>
            <li id="upcoming"><a rel ="upcoming" href="javascript:;">Upcoming</a></li>
            <li id="past"><a rel="past" href="javascript:;">Past</a></li>
        </ul>
        <div class="spacer"></div>
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="dyntable" id="events-data-table">
            <thead>
                <tr>
                    <td id="event_del" colspan="6" style="padding:0">
                        <div class="sTableOptions" style="border:none 0">
                                <a class="button delete" id="deleteAll">
                                <span>Delete</span>
                                </a>
                        </div>
                       
                    </td>
                </tr>
                <tr>
                    <th width="5%" class="head0"><input type="checkbox" id="master_checkbox"></th>
                    <th width="15%" class="head1">Event Date</th>
                    <th width="40%" class="head0">Event Title</th>
                    <th width="18%" class="head1">Event Location</th>
                    <th width="10%" class="head0">Invitee</th>
                    <th width="12%" class="head1">Action</th>
                </tr>

            </thead>
        </table>
        <div class="hidden">
            <span class="aphabetical_filters">
                <?php
                /*foreach (range('A', 'Z') as $char) {
                    echo '<a href="javascript:;" class="letter_filter">' . $char . '</a> &nbsp;';
                }*/
                ?>
            </span>
        </div>
    </div>
</div>
<div id="dialog-confirm" title="Are You Sure You Want to Delete?" style="display:none;">
    <p>  <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Event will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>

<script type="text/javascript">
 $(document).ready( function($) {
    $("#wait1").hide();
    if(('<?php echo $this->event_title?>') !=""){
        $.jGrowl('<?php echo $this->event_title?>'+" has been added.");
    }
    if(('<?php echo $this->event_title_edit?>') !=""){
        $.jGrowl('<?php echo $this->event_title_edit?>'+" has been edited.");
    }
    $(".reports").parent().addClass('current');
 });
</script>
<script type="text/javascript">
    /** Datatable code **/
    var oTable;
    var page='all';
    var alphabet_list = jQuery(".hidden").html();
    $(document).ready( function($) {
        $('#master_checkbox').removeAttr("checked");
    });
    $(document).on('click',"#events-data-table_paginate a", function(){
         $('#master_checkbox').removeAttr("checked");
    })
    $(window).bind('load',function(){        
        $("#page_select").find("a").click(function(){
            page = ($(this).attr('rel'));
            $("#all").removeClass("current")
            $("#upcoming").removeClass("current")
            $("#past").removeClass("current")
            $("#"+page).addClass("current")
            oTable.fnDestroy();
            init_oTable_initialize(page);
          });
        init_oTable_initialize(page);
        init_alphabetical_filters();
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_vendor_link();
        init_col_color();
        init_row_delete();
        init_toggleChecked();
        init_delet_all_checked();
        init_edit();
    });
    function init_oTable_initialize(page){
        $('#master_checkbox').removeAttr("checked")
        oTable=$('#events-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "iDisplayLength": 10,
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/event/ajax-Get-Events-Dt/targetPage/'+page,
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Events by Title:"
            },
            "aaSorting": [[1,'desc']], // Initial sorting order when page loads
            "aoColumnDefs":[{ "bSortable": false, "aTargets": [ 0 ] },{ "bSortable": true, "aTargets": [ 1 ] },{ "bSortable": true, "aTargets": [ 2 ] },{ "bSortable": true, "aTargets": [ 3 ] },{ "bSortable": false, "aTargets": [ 4 ] },{ "bSortable": false, "aTargets": [ 5 ] }],   // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {
                //$('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after(alphabet_list);
            }
        } );
    }
    function init_vendor_link(){
        $(document).on("click", "a.vendor_link", function(){
            window.location.href=site_url+"/admin/vendors/view/id/"+$(this).attr('rel');
        });
    }

    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                oTable.fnDraw();
                return;
            }
        });
    }

    function init_alphabetical_filters(){
        $(document).on('click', '.letter_filter',function(){
            oTable.fnDestroy();
            init_oTable_initialize(page);
            oTable.fnFilter($(this).text());
        });
    }

    function init_col_color(){
        //oTable.$('td').addClass('')
    }

    function row_delete(eventId, pageTitle){
         //$(document).on('click', '.deleteuser',function(){
            //var pageTitle = ($(this).attr('title'));
            //var eventId = ($(this).attr('rel'));
            var message = pageTitle + " will be permanently deleted and cannot be recovered. Are you sure?";
            $("#dialog-confirm").text(message);
            $( "#dialog:ui-dialog" ).dialog( "destroy" );
            $( "#dialog-confirm" ).dialog({
                resizable: false,
                height:'auto',
                modal: true,
                buttons: {
                    "Delete": function() {
                        var mine = $( this )
                        $.ajax({
                            type : 'post',
                            url: site_url+'/admin/event/delete-event/',
                            data:'eventId='+eventId,
                            success: function(response) {                                
                                mine.dialog( "close" );
                                $('#master_checkbox').removeAttr("checked");
                                oTable.fnDraw();
                                $.jGrowl(pageTitle+" has been deleted.");
                            }
                        });
                    },
                    "Cancel": function() {
                        $( this ).dialog( "close" );
                    }
                }
            });       
        // });
    }
    function init_row_delete(){
        $(document).on('click', '.deleteuser',function(){
            var eventId = ($(this).attr('rel'));
            var pageTitle = '"'+($(this).attr('title'))+'"';
            row_delete(eventId,pageTitle);
        });
    }

    function init_toggleChecked() {        
        $(document).on('click', '#master_checkbox',function(){
            var status = this.checked;
            $(".checkbox").each( function() {
                $(this).attr("checked",status);
            })
        })
    }

    function init_delet_all_checked(){
         $(document).on('click', '#deleteAll', function(){
            var checkedCheckboxes = $("input:checkbox[name=event_name]:checked");
            var selectedValues="";
            if(checkedCheckboxes[0] === undefined){
                $.jGrowl("Please select event(s) to delete.");
            }
            else{
                var i=0;
                checkedCheckboxes.each(function () {
                   if(i==0){
                     selectedValues = $(this).attr('rel')
                   }
                   else{
                     selectedValues +=  ","+$(this).attr('rel');
                   }
                   i++;
                });
                row_delete(selectedValues,"Selected event(s)");
            }            
         })        
    }

    function init_edit(){
        $(document).on('click', '.view', function(){
            document.location = '<?php echo $this->baseUrl("admin/event/edit/id/") ?>'+$(this).attr('rel');
        });
    }

   
    /** Datatable code **/
</script>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px;
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }

    #events-data-table { border-collapse: collapse; }
    #events-data-table tr td { padding: 8px 10px; border-right: 1px solid #fff; border-bottom: 1px solid #ddd; vertical-align: top;}
    #events-data-table thead th { padding: 8px 10px; color: #ccc; text-shadow: 1px 1px #444; font-size: 12px; text-transform: uppercase; border-right: 1px solid #fff; }
    #events-data-table thead th { font-weight: normal; text-align: left; }
    #events-data-table tr td:last-child { border-right: 0; }
    #events-data-table tr:last-child td { border-bottom: 0;}
    #events-data-table tr:hover { background: #cacaca; }
    #events-data-table tr.selected { background: #fffccc; }
   
   
    #events-data-table .odd { background-color: #eaeaea; }
    #events-data-table .even { background-color: #ddd; }
    div.jGrowl.top-right {
	right: 				0px;
	top: 				100px;
    }
    div.jGrowl div.jGrowl-notification{
           color:#000000;
           background:#A79269 ;
    }
    

    
</style>   





