<div id="login_wrap">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>    
<!--    <h1 class="h1"> Thank you for registering with Greek Licensing. 
        We will review the information you have submitted and get back to you upong review.<br /><br />
        If you have any question in the meantime, please contact Melissa Jean-Baptiste.<br /><br />
        Licensing Department<br />
        e: Registration@greeklicensing.com<br />
        p: 760-734-6764 ext. 140<br />
        f:  707-202-0532<br />
    </h1>-->
    <span style="padding-left: 25px;padding-right: 25px;display:block;color:#333333;font-family: DroidSansRegular,Segoe UI,Lucida Sans Unicode,Lucida Grande,sans-serif;">
    <h5 >
    Thank you!<br /> You are now registered and may log in to your account using the information you have just provided.
    </h5>
    </span>
</div>
