<?php
//print_r($this->events);
?>
<div id="view-content">
    <h3>Notification Details</h3>
    <hr size="1" noshade />

    <div class="one">
        <div class="left_div">
            <h3>Date:</h3> 
        </div>
        <div class="right_div">
        <?php echo $this->notifications->time->format('M d, Y h:ia'); ?>
        </div>
    </div>      
    <div class="spacer clear"></div>

    <div clas="one">
        <div class="left_div">
            <h3>Title:</h3>
        </div>
        <div class="right_div">
            <?php echo html_entity_decode($this->notifications->title); ?>
        </div>
    </div>               
    <div class="spacer clear"></div>

    <div class="one">
        <div class="left_div">
            <h3>Message:</h3>
        </div>
        <div class="right_div">
            <?php echo html_entity_decode($this->notifications->message); ?>
        </div>
    </div>
</div>

<style type="text/css">
    .left_div{width: 15%; height: auto; float: left;}
    .right_div{width: 75%; height: auto; margin-left: 0px; float: left;}
    .one{width: 100%;}
</style>


