<h2>Create Addendum</h2>
<div class="one">
    <a href="<?php echo $this->baseUrl("admin/clients/master-templates"); ?>" class="iconlink<?php echo $this->noinsurance ? "" : "2"; ?>"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/<?php echo $this->noinsurance ? "white" : "black"; ?>/settings.png" class="mgright5" alt="" /><span>With Insurance</span></a> &nbsp; 
    <a href="<?php echo $this->baseUrl("admin/clients/master-templates/noinsurance/1"); ?>" class="iconlink<?php echo $this->noinsurance ? "" : "2"; ?>"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/<?php echo $this->noinsurance ? "white" : "black"; ?>/settings.png" class="mgright5" alt="" /><span>Without Insurance</span></a> &nbsp;     
    <a href="<?php echo $this->baseUrl("admin/clients/addendums"); ?>" class="iconlink"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/white/settings.png" class="mgright5" alt="" /><span>Addendums</span></a> &nbsp;                                  
</div>

<form action="" method="post" id="addendum_form">
    Describe briefly the reason for the addendum:<br />
    <?php echo $this->form->reason; ?>
    <div class="spacer"></div>
    Enter the addendum below:<br />
    <?php echo $this->form->content; ?>
    <div class="spacer"></div>
    <?php echo $this->form->save; ?>    
    <div class="spacer"></div>
    <b>Select the Greek organizations for which this addendum would apply.</b><br />
    <?php if(sizeof($this->clients)) {?>
    <div class="greek_name">
        <ul>
            <?php foreach($this->clients as $client) {?>
            <li><?php echo $this->form->greek_org->setCheckedValue($client['id'])." ".$client['greek_name']; ?></li>
            <?php }?>
        </ul>
    </div>
    <?php }?>
    <div class="spacer"></div>
    <div class="greek_name">
        If you submit the changes above, then all active vendors will be notifies of the new addendum. Vendors will be asked to agree to the changes. They will be given till July 1 of the new fiscal year to agree to the addendum. If they do not agree to the new addendum, they will be locked out of the system. 
        <div class="spacer"></div>
        <u>Please make sure the changes are final before clicking on the "<b>Submit</b>" button.</u>
    </div>
    <div class="spacer"></div>
    <?php echo $this->form->is_draft; ?>
    <?php echo $this->form->submit; ?>    
</form>

<script type="text/javascript">
tinyMCE.init({
        mode : "exact",
        elements : "content",
        theme : "advanced",
        height: "400",
        width: "800",
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor,hr,removeformat,visualaid,|,sub,sup,|,charmap",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_path : false,
        theme_advanced_font_sizes: "8px, 9px, 10px, 11px, 12px,14px,16px,18px,20px,24px,28px,36px,44px",
        font_size_style_values : "13px, 14px,16px,18px,20px",
        content_css : "<?php echo $this->baseUrl("assets"); ?>/css/custom_content.css",
        force_br_newlines : true,
        force_p_newlines : false,
        forced_root_block : "",
        theme_advanced_resizing : true,
        skin : "o2k7",
        skin_variant : "silver"
    });
    $(function(){
        $('#submit, #save').click(function(){
                this.id == 'save' ? $('#is_draft').val('1') : $('#is_draft').val('0');
        });
    });
</script>
<style type="text/css">    
    #addendum_form .greek_name {width:850px;border: 1px solid #ccc;display: inline-block;padding:5px;}
    .greek_name ul {list-style: none;}
    .greek_name ul li {width:70px;float:left;}
    .success {color:green}
    .errors {color:red}
</style>