<link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/tabs-no-images.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/jquery-ui/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/jquerytools/jquery.tools.min.js"></script>

<div class="one">
    <!-- tabs -->
    <ul class="css-tabs">
        <li><a id="t1" href="#">Setup</a></li>
        <li><a id="t2" href="#">Legal</a></li>
        <li><a id="t3" href="#">Operations</a></li>
        <li><a id="t4" href="#">Royalty</a></li>
        <li><a id="t5" href="#">Notes</a></li>
        <li><a id="t6" href="#">Lic. Template</a></li>
    </ul>
    
    <!-- panes -->
    <div class="css-panes">
        <div><!-- setup --></div>
        <div><!-- legal --></div>
        <div><!-- operation --></div>
        <div><!-- Royalty --></div>
        <div><!-- note --></div>
        <div>
            <div class="one">
                <a href="<?php echo $this->baseUrl("admin/clients/add-lic-template/id/{$this->client->id}"); ?>" class="iconlink<?php echo $this->noinsurance ? '2' : ''?>"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/<?php echo $this->noinsurance ? "black" : "white"; ?>/settings.png" class="mgright5" alt="" /><span>With Insurance</span></a>&nbsp;
                <a href="<?php echo $this->baseUrl("admin/clients/add-lic-template/id/{$this->client->id}/noinsurance/1"); ?>" class="iconlink<?php echo $this->noinsurance ? '' : '2'?>"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/<?php echo $this->noinsurance ? "white" : "black"; ?>/settings.png" class="mgright5" alt="" /><span>Without Insurance</span></a>
            </div>
            <div class="spacer"></div>
            <?php if(sizeof($this->message)) { ?>
                <div class="<?php echo $this->message['success'] ? 'success' : 'errors'?>"><?php echo $this->message['message']?></div>
                <div class="spacer clear"></div>
            <?php } ?>
            
            <form action="" method="post" id="license_template">
                <?php echo $this->form->template; ?>
                <div class="spacer"></div>
                <button type="submit" class="button button_black detail_button">Save</button>
            </form>
            <div class="clear"></div>
        </div>
    </div>
</div>

<style type="text/css">
    .errors{
        list-style: none;
        color:red;
    }
    .grid_12{
        margin-left: 0%;
        margin-right: 0%;
    }
    .grid_9{
        margin-left: 0%;
        margin-right: 0%;
    }
    .grid_4{
        margin-left: 0%;
        margin-right: 0%;
        margin-top:3px;
    }
    .grid_3{
        margin-left: 0%;
        margin-right: 0%;
        margin-top:3px;
    }
    .grid_2{
        margin-left: 0%;
        margin-right: 0%;
        margin-top:3px;
    }

    div.jGrowl div.jGrowl-notification
    {
        color:#000000;
        background-color:#A79269;
    }
    .ui-autocomplete-loading
    {
        background: white url('<?php echo $this->baseUrl("assets"); ?>/images/loading.gif') right center no-repeat;
    }    
    .success {color:green}
    .errors {color:red}
</style>

<script type="text/javascript">
$(document).ready(function() {

    $(".css-tabs:first").tabs(".css-panes:first > div",{initialIndex: 5})
        .bind("onBeforeClick onClick", function(event,index) {
            return false;
        });



    tinyMCE.init({
        mode : "exact",
        elements : "template",
        theme : "advanced",
        height: "500",
        width: "800",
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor,hr,removeformat,visualaid,|,sub,sup,|,charmap",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_path : false,
        theme_advanced_font_sizes: "8px, 9px, 10px, 11px, 12px,14px,16px,18px,20px,24px,28px,36px,44px",
        font_size_style_values : "13px, 14px,16px,18px,20px",
        content_css : "<?php echo $this->baseUrl("assets"); ?>/css/custom_content.css",
        force_br_newlines : true,
        force_p_newlines : false,
        forced_root_block : "",
        theme_advanced_resizing : true,
        skin : "o2k7",
        skin_variant : "silver"
    });

});
</script>
