<h2>Add A Contact</h2>
<hr size="1" noshade />

<form action="" method="POST" enctype="multipart/form-data" id="<?php echo $this->form->getName(); ?>">    
    <?php echo $this->form->editContact; ?>
    <div class="spacer"></div>
    <div class="form_container_left">
        <div class="one_third">
            <?php echo $this->form->sal; ?>
        </div>
        <div class="one_third">
            <?php echo $this->form->first_name; ?>
        </div>
        <div class="one_fifth">
            <?php echo $this->form->last_name; ?>
        </div>
        <div class="clear"></div>                
        <?php echo $this->form->title; ?>                
        <div class="clear"></div>
        <?php echo $this->form->email; ?>
        <div class="spacer"></div>
        <?php echo $this->form->contact_type; ?>        
        <div class="clear"></div>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->phone; ?>
        <?php echo $this->form->phone_ext; ?>
        <?php echo $this->form->mobile; ?>      
        <div class="spacer"></div>
        <div class="spacer"></div>        
    </div>
    <div class="clear"></div>
    <button type="submit" id="submitEdit" class="button button_black detail_button" style="float: left;">Submit</button>   
    <div class="clear"></div>
</form>

<style type="text/css">
    #first_name, #last_name, #city, #state, #zipcode, #sal{
        width:110px;
    }    
</style>    

<script type="text/javascript">
    $(window).bind('load', function(){
        event_functions._initialize();
        
    });
    
    event_functions = {
        _initialize : function(){
            if(('<?php echo $this->msg; ?>') != ""){      
                window.parent.execute_parent('<?php echo $this->msg; ?>');
            }   
        }
    }    
</script>