<?php
//$this->placeholder('main_side_bar')->captureStart();
//echo $this->partial('clients/sidebar-menus.phtml', array('selected' => 'operations', 'id' => $this->client->id));
//$this->placeholder('main_side_bar')->captureEnd();
?>
<link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl("assets"); ?>/css/tabs-no-images.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/jquery-ui/jquery-ui-timepicker-addon.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/jquerytools/jquery.tools.min.js"></script>

<div class="one">
    <!-- tabs -->
    <ul class="css-tabs">
        <li><a id="t1" href="#">Setup</a></li>
        <li><a id="t2" href="#">Legal</a></li>
        <li><a id="t3" href="#">Operations</a></li>
        <li><a id="t4" href="#">Royalty</a></li>
        <li><a id="t5" href="#">Notes</a></li>
        <li><a id="t6" href="#">Lic. Template</a></li>
    </ul>

    <!-- panes -->
    <div class="css-panes">
        <div><!-- setup --></div>
        <div><!-- legal --></div>
        <div>
<!--        <h2><?php echo $this->client->organization_name; ?></h2>
            <hr size="1" />-->
            <div class="spacer"></div>
            <form action="" method="POST" enctype="multipart/form-data" id="client_setup_form">
                <div class="form_container_left">
                    <?php echo $this->form->license_agreement_signee; ?>
                    <?php echo $this->form->signee_title; ?>
                    <?php echo $this->form->org_magazine_circulation_size; ?>
                    <?php echo $this->form->frequency_of_mag; ?>
                    <?php echo $this->form->accept_advertising; ?>
                    <?php echo $this->form->advertising_rates; ?>
                    <?php echo $this->form->advertising_deadlines; ?>
                    <?php echo $this->form->workshop_names; ?>
                    <?php echo $this->form->org_workshop_type; ?>
                    <div class="spacer"></div>
                    <button type="submit" class="button button_black detail_button">Save</button>
                </div>
                <div class="form_container_right">
                    <?php echo $this->form->org_workshop_dates; ?>
                    <?php echo $this->form->convention_name; ?>
                    <?php echo $this->form->org_convention_site; ?>
                    <?php echo $this->form->org_convention_dates; ?>
                    <?php echo $this->form->org_pms_colors_1; ?>
                    <?php echo $this->form->org_pms_colors_2; ?>
                    <?php echo $this->form->org_pms_colors_3; ?>
                    <?php echo $this->form->org_pms_colors_4; ?>
                    <?php echo $this->form->default_note_to_all_applying_vendors; ?>
                </div>
            </form>
            <div class="clear"></div>
        </div>
        <div><!-- Royalty --></div>
        <div><!-- Notes --></div>
        <div><!-- Lic. Template --></div>
    </div>
</div>

<style type="text/css">
    .errors{
        list-style: none;
        color:red;
    }
    .grid_12{
        margin-left: 0%;
        margin-right: 0%;
    }
    .grid_9{
        margin-left: 0%;
        margin-right: 0%;
    }
    .grid_4{
        margin-left: 0%;
        margin-right: 0%;
        margin-top:3px;
    }
    .grid_3{
        margin-left: 0%;
        margin-right: 0%;
        margin-top:3px;
    }
    .grid_2{
        margin-left: 0%;
        margin-right: 0%;
        margin-top:3px;
    }

    div.jGrowl div.jGrowl-notification
   {
       color:#000000;
       background-color:#A79269;
   }
    .ui-autocomplete-loading
       {
            background: white url('<?php echo $this->baseUrl("assets"); ?>/images/loading.gif') right center no-repeat;
      }
</style>
<script type="text/javascript">
$(document).ready(function() {

    $(".css-tabs:first").tabs(".css-panes:first > div",{initialIndex: 2})
        .bind("onBeforeClick onClick", function(event,index) {
            return false;
        });


    var cur_year = "<?php echo date('Y') ?>";
        var cur_month = "<?php echo date('m') - 1 ?>";
        var cur_day = "<?php echo date('d') ?>";
        $("#org_workshop_dates, #org_convention_dates, #advertising_deadlines").datetimepicker({
            minDate: new Date(cur_year, cur_month, cur_day, 8, 30),
            maxDate: new Date(2030, 11, 31, 17, 30), showHour:false,showMinute:false,showSecond:false,timeText:"",timeFormat: '',currentText:"Today"
        });


});
</script>