<?php if (!sizeof($this->data)): ?>
    <div class="notification msginfo">No Data Found matching your criteria</div>
<?php else: ?>
    <table cellpadding="0" cellspacing="0" class="sTable2" id="userlist" width="100%">
        <thead>
            <tr>
                <td>Company Name</td>
                <td>Date</td>
                <td>Check #</td>
                <td align="right">Total Amount</td>
                <td align="right">AMC</td>
                <td align="right"><?php echo $this->client->organization_name; ?></td>
                <td>Sharing</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $data): ?>
                <tr>
                    <td><?php echo $data['organization_name']; ?></td>
                    <td><?php echo $data['date']; ?></td>
                    <td><?php echo $data['check_num']; ?></td>
                    <td><?php echo $data['total']; ?></td>
                    <td><?php echo $data['AMC']; ?></td>
                    <td><?php echo $data['AMC']; ?></td>
                    <td><?php echo ($data['sharing']) ? "Yes" : "No"; ?></td>
                    
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
