<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('clients/sidebar-menus.phtml',array('selected'=>'change_password','id'=>$this->client->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<h2>Reset Password</h2>
<hr size="1" noshade />
<div class="spacer clear"></div>

<form action="" method="POST" enctype="multipart/form-data">
    <div class="form_container_left">
        <?php echo $this->form->username; ?>
        <div class="clear"></div>
        <?php echo $this->form->recovery_email; ?>
        <div class="clear"></div>
        <?php echo $this->form->old_password; ?>
        <div class="clear"></div>
        <?php echo $this->form->password; ?>
        <div class="clear"></div>
        <?php echo $this->form->repassword; ?>
        <div class="clear"></div>
        <?php echo $this->form->Submit; ?>
    </div>
</form>