<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('clients/sidebar-menus.phtml',array('selected'=>'correspondence','id'=>$this->client->id));
$this->placeholder('main_side_bar')->captureEnd();
?>

<div class="one">
    <div class="one_third">
        <h2><?php echo $this->client->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Client Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->client->user_status)); ?></h4>       
        </div>
    </div>        
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<?php echo $this->partial('clients/correspondence-form-partial.phtml', array('form' => $this->form, 'client' => $this->client)); ?>

<div class="spacer"></div>

<table cellpadding="0" cellspacing="0" border="0" class="dyntable" id="correspondence-data-table">
    <thead>
        <tr>
            <th class="head1" width="15%">Date</th>
            <th class="head0" width="23%">Subject</th>
            <th class="head1" width="50%">Note</th>
            <th class="head0" width="12%">Action</th>
        </tr>            
    </thead>
</table>

<script type="text/javascript">
    /** Datatable code **/
    var oTable;
    $(window).bind('load',function(){
        oTable=$('#correspondence-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "iDisplayLength": 10,            
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/clients/ajax-get-correspondence/id/<?php echo $this->client->id; ?>',
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Correspondence:"                
            },
            "aaSorting": [[0,'desc']], // Initial sorting order when page loads
            "aoColumnDefs":[
                { "bSortable": true, "aTargets": [ 0 ] },
                { "bSortable": true, "aTargets": [ 1 ] },
                { "bSortable": false, "aTargets": [ 2 ] },
                { "bSortable": false, "aTargets": [ 3 ] }],  // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {
                $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
            },
            fnDrawCallback:function(){
                init_client_link();
            }            
        } ); 
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_client_link();
    });    
    
    function init_client_link(){
        $(document).on('click', 'a.clients_notes_link', function(){
            var $url = site_url+'/admin/clients/ajax-get-correspondence-details/note-id/'+$(this).attr('rel');
            loadPopupView($url, 750, 465); 
        });
        
        $(document).on('click', 'a.edit_notes_link', function(){
            var $url = site_url+'/admin/clients/edit-correspondence/note-id/'+$(this).attr('rel');             
            loadPopupView($url, 750, 465); 
        });
        
    
    /*
        $("a.clients_notes_link").each(function(){                         
            $(this).qtip(
            {
                content: {
                    text: 'Loading..',      
                    title: {
                        text: 'Note Details', // Give the tooltip a title using each elements text
                        button: false
                    },
                    ajax: {
                        url: site_url+'/admin/clients/ajax-get-correspondence-details/note-id/'+$(this).attr('rel')
                    }
                },
                position: {
                    my: 'center', // ...at the center of the viewport
                    at: 'center',
                    target: $(window),
                    viewport: $(window),
                    effect: false
                    
                },
                show: {
                    event: 'click', 
                    solo: true, 
                    modal: true 
                },
                hide: 'unfocus',
                style: {
                    width:'800px',
                    classes : 'ui-tooltip-shadow ui-tooltip-light ui-tooltip-rounded'
                }
            })
            .click(function(event) { event.preventDefault(); });
        });*/
    }
    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                return;
            }
        });
    }
    
    function init_alphabetical_filters(){
        $('.letter_filter').on('click',function(){
            oTable.fnFilter($(this).text());
        });
    }
    /** Datatable code **/
    
    $(function(){
        $(document).on('click', 'a.delete_note', function(){
            if(confirm('Are you sure to delete this note ?')){
                $note_id=$(this).attr('rel').split("-")[1];
                $.ajax({
                    url:site_url+'/admin/clients/ajax-delete-correspondence/',
                    dataType:'json',
                    data : 'note_id='+$note_id+'&cid='+<?php echo $this->client->id; ?>,
                    type:'post',
                    success:function(e){
                        $.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                        if(e.code=='success'){
                            oTable.fnDraw();
                        }
                    }
                });
            }
            return false;
        });
    })
    
    // function to load popup
    function loadPopupView(url, w, h){
        $.fancybox({
            'width'                 : w,
            'height'                : h,
            'href'                  : url,    
            'transitionIn'          : 'none',
            'transitionOut'         : 'none',
            'padding'               : 20,
            'speedIn'               : 0,
            'type'                  : 'iframe',
            'changeSpeed'           : 0,            
            'changeFade'            : 0,
            'speedIn'               : 100,
            'speedOut'              : 100,
            'overlayColor'          : '#FFF',
            'onClosed'              : function() {
                // window.location = $obj.attr('param');
            }
        });        
        return false;
    }
    
    function close_popup(){
        $.fancybox.close();
    }
    
    function execute_refresh(message){
        close_popup();
        oTable.fnDraw();
        $.jGrowl(message);                   
    }
</script>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px; 
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
    .ui-tooltip-content{
        font-size:110%;
        line-height: 150%
    }
    .ui-tooltip, .qtip{
        max-width: 500px; 
    }
</style>   
