<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('clients/sidebar-menus.phtml',array('selected'=>'legal','id'=>$this->client->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<style type="text/css">
    div.jGrowl div.jGrowl-notification
    {
        color:#000000;
        background-color:#A79269;
    }
</style>

<div class="one">
    <div class="one_third">
       <h2><?php echo $this->client->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Client Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->client->user_status)); ?></h4>       
        </div>
    </div>        
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<form action="" method="POST" enctype="multipart/form-data" id="client_setup_form">
    <div class="form_container_left">
        <?php echo $this->form->org_choice_law; ?>
        <?php echo $this->form->licensor_title; ?>
        <?php echo $this->form->legal_name; ?>
        <?php echo $this->form->legal_firm; ?>
        <?php echo $this->form->legal_address1; ?>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->legal_address2; ?>
        <?php echo $this->form->legal_city; ?>
        <?php echo $this->form->legal_state; ?>
        <?php echo $this->form->legal_zip; ?>
        <?php echo $this->form->legal_phone; ?>
    </div>
            <div class="spacer"></div>
        <button type="submit" class="button button_black detail_button">Save</button>
</form>