<h2>Master License Template</h2>
<div class="spacer"></div>
<?php //echo $this->partial('clients/master_template_menus.phtml', array('noinsurance' => $this->noinsurance)); ?>
<div class="one">    
    <a href="<?php echo $this->baseUrl("admin/clients/master-templates"); ?>" class="iconlink<?php echo $this->noinsurance ? "2" : ""; ?>"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/<?php echo $this->noinsurance ? "black" : "white"; ?>/settings.png" class="mgright5" alt="" /><span>With Insurance</span></a> &nbsp; 
    <a href="<?php echo $this->baseUrl("admin/clients/master-templates/noinsurance/1"); ?>" class="iconlink<?php echo $this->noinsurance ? "" : "2"; ?>"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/<?php echo $this->noinsurance ? "white" : "black"; ?>/settings.png" class="mgright5" alt="" /><span>Without Insurance</span></a> &nbsp;     
    <a href="<?php echo $this->baseUrl("admin/clients/addendums"); ?>" class="iconlink2"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/black/settings.png" class="mgright5" alt="" /><span>Addendums</span></a> &nbsp;                      
</div>
<div class="spacer"></div>
<div class="spacer"></div>

<?php if(sizeof($this->message)) {?>
    <div class="<?php echo $this->message['success'] ? 'success' : 'errors'?>"><?php echo $this->message['message']?></div>
<?php }?>
    
<div class="spacer"></div>
<form action="" method="post" id="license_template">
    <?php echo $this->form->template; ?>
    <div class="spacer"></div>
    <?php //echo $this->form->save; ?>
    <button type="submit" class="button button_blue detail_button">Save</button>
    <button type="button" id="preview_pdf" class="button button_blue detail_button">Preview in PDF</button>
    <div id="submit_wait1" style="width:150px; float:right; display:none">Loading PDF&nbsp; <img src="<?php echo $this->baseUrl("assets/images/loading.gif"); ?>" /></div>
</form>

<script type="text/javascript">
tinyMCE.init({
        mode : "exact",
        elements : "template",
        theme : "advanced",
        height: "500",
        width: "800",
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor,hr,removeformat,visualaid,|,sub,sup,|,charmap",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_path : false,
        theme_advanced_font_sizes: "8px, 9px, 10px, 11px, 12px,14px,16px,18px,20px,24px,28px,36px,44px",
        font_size_style_values : "13px, 14px,16px,18px,20px",
        content_css : "<?php echo $this->baseUrl("assets"); ?>/css/custom_content.css",
        force_br_newlines : true,
        force_p_newlines : false,
        forced_root_block : "",
        theme_advanced_resizing : true,
        skin : "o2k7",
        skin_variant : "silver"
    });
    
        function review_pdf(){
        var agreement = encodeURIComponent(tinyMCE.getInstanceById('template').getBody().innerHTML);
        $('#template').val(tinyMCE.getInstanceById('template').getBody().innerHTML);
        $.ajax({
                url:'<?php echo $this->baseUrl("admin/clients/printinpdf/")?>',
                type: "POST",
                data:$('#license_template').serialize()+'&template'+ agreement,
                dataType: 'json', 
                beforeSend: function() { $('#submit_wait1').show(); },
                complete: function() { $('#submit_wait1').hide();},
                success: function(msg) {                    
                    pdf_url = msg.name
                    $.fancybox({
                        'href'                  : site_url+"/admin/clients/pdflink/filename"+pdf_url,
                        'height'                : 40,
                        'width'                 : 300,
                        'autoScale'             : true,
                        'autoDimensions'        : true,
                        'transitionIn'          : 'none',
                        'transitionOut'         : 'none',
                        'type'                  : 'iframe',
                        'transitionIn'     : 'none',
                        'transitionOut'     : 'none',
                        'speedIn'      : 100,
                        'speedOut'      : 100,
                        'overlayShow'     : true,
                        'overlayColor'     : "#FFF",
                        'onClosed'              : function() {
                            // window.location = $obj.attr('param');
                        }
                    });
                }
            });      
    }
    
    $(document).on('click','#preview_pdf', function(){
       review_pdf();       
    });
</script>
<style type="text/css">
    .link_button {border: none;}
/*    .link_button a.current {background-color: #654b24;}*/
    .success {color:green}
    .errors {color:red}
</style>
