<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('reports/reports-sidebar-menus.phtml');
$this->placeholder('main_side_bar')->captureEnd();
?>
<div class="one">
    <div><a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'export-pdf', 'module' => 'admin', 'year' => $this->year, 'clientId' => $this->clientId, 'quarter' => $this->quarter)); ?>" class="iconlink2"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/pdf.png" class="mgright5" alt="" /><span>Export to PDF</span></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'export-csv', 'module' => 'admin', 'year' => $this->year, 'clientId' => $this->clientId, 'quarter' => $this->quarter)); ?>" class="iconlink2"><span>Export to CSV</span></a>
    </div>
    <div style="float: right;"><a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'affinity-report-detail', 'module' => 'admin', 'year' => $this->year, 'clientId' => $this->clientId, 'quarter' => $this->quarter)); ?>" class="iconlink2"><span>View Affinity Report</span></a></div>
    <div class="one_fourth"><h2 class="grid_cap">Royalty Report Detail</h2></div>
</div>
<div class="spacer"></div>
<table cellpadding="0" cellspacing="0" border="0" class="dyntable sTable2" id="reports-data-table">
    <thead>
        <tr>
            <th class="head0" width="30%">Company Name</th>
            <th class="head1">Date</th>
            <th class="head0">Pmt Type</th>
            <th class="head1">Ref#</th>
            <th class="head0">Total Amount</th>
            <th class="head1">Affinity</th>
            <th class="head0"><?php echo $this->clientDetail ? $this->clientDetail->organization_name : ''; ?></th>
            <th class="head1">Sharing</th>
        </tr>
    </thead>
    <?php
    $totalClientAmount = 0;
    foreach ($this->reportDetail as $item) {
	?>
	<?php
	$amcAmount = 0;
	$clientAmount = 0;

	if (isset($item->pmt_id->invoice)) {

	    if (($item->amount_paid) && $item->pmt_id->invoice->invoice_type != 'Refund') {
		$totalAmount = $item->amount_paid;
		if ($item->sharing == 1) {
		    $amcAmount = ($item->amount_paid * $item->percent_amc);
		}
		$clientAmount = $item->amount_paid - $amcAmount;
	    } elseif (($item->late_paid) && $item->pmt_id->invoice->invoice_type != 'Refund') {
		$totalAmount = $item->late_paid;
		if ($item->sharing == 1) {
		    $amcAmount = ($item->late_paid * $item->percent_amc);
		}
		$clientAmount = $item->late_paid - $amcAmount;
	    } elseif (($item->adv_paid) && $item->pmt_id->invoice->invoice_type != 'Refund') {
		$totalAmount = $item->adv_paid;
		if ($item->sharing == 1) {
		    $amcAmount = ($item->adv_paid * $item->percent_amc);
		}
		$clientAmount = $item->adv_paid - $amcAmount;
	    } else {
		$amcAmount = 0;
		$clientAmount = 0;
		$totalAmount = 0;
	    }
	} else {
	    if (($item->amount_paid)) {
		$totalAmount = $item->amount_paid;
		if ($item->sharing == 1) {
		    $amcAmount = ($item->amount_paid * $item->percent_amc);
		}
		$clientAmount = $item->amount_paid - $amcAmount;
	    } elseif (($item->late_paid)) {
		$totalAmount = $item->late_paid;
		if ($item->sharing == 1) {
		    $amcAmount = ($item->late_paid * $item->percent_amc);
		}
		$clientAmount = $item->late_paid - $amcAmount;
	    } elseif (($item->adv_paid)) {
		$totalAmount = $item->adv_paid;
		if ($item->sharing == 1) {
		    $amcAmount = ($item->adv_paid * $item->percent_amc);
		}
		$clientAmount = $item->adv_paid - $amcAmount;
	    } else {
		$amcAmount = 0;
		$clientAmount = 0;
		$totalAmount = 0;
	    }
	}
	?>
        <tr>
    	<td><?php echo $item->pmt_id->vendor->organization_name; ?></td>
    	<td><?php echo $item->last_modified_date->format("m/d/Y"); ?></td>
    	<td><?php echo $item->pmt_id->invoice ? str_replace('Received', '', $item->pmt_id->invoice->payment_status) : "N/A"; ?></td>
    	<td><?php echo $item->pmt_id->check_num; ?></td>
    	<td><?php echo $this->currency->toCurrency($totalAmount); ?></td>
    	<td><?php echo $this->currency->toCurrency($amcAmount); ?></td>
    	<td><?php echo $this->currency->toCurrency($clientAmount); ?></td>
    	<td><?php echo $item->sharing ? 'Yes' : 'No'; ?></td>
        </tr>
	<?php
	$totalClientAmount = $totalClientAmount + $clientAmount;
    }
    ?>
    <tr>
        <td colspan="6" align="right"><strong>Total Amount for Quarter:</strong></td>
        <td><?php echo $this->currency->toCurrency($totalClientAmount); ?></td>
        <td></td>
    </tr>
</table>
<br>
<div>
    <a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'export-pdf', 'module' => 'admin', 'year' => $this->year, 'clientId' => $this->clientId, 'quarter' => $this->quarter, 'postToClient' => 'yes')); ?>" class="iconlink2"><span>Post to client profile</span></a>
    <strong>Last Posted Date : </strong><?php
    if ($this->lastPostDate) {
	echo $this->lastPostDate->format("m/d/Y");
    } else {
	echo 'N/A';
    }
    ?>
</div>
<style type="text/css">
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
    .sTable2 tbody tr.selected td{
        background-color: #FFFFCC;
    }
    .fancybox-title-inside{
        text-align: left;
    }
    .leftalign{float: left;}
    .rightalign{float: right;}
    .Pending {
        color: #FF6600;
    }
    .Approved {
        color: #078000;
    }
    .Rejected {
        color: #FF0000;
    }
    .Past {
        color: #FF0000;
    }

</style>
