<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('clients/client-sidebar-menus.phtml');
$this->placeholder('main_side_bar')->captureEnd();
?>

<form id="downloader" method="post">
    <input type="hidden" name="current_search_params" id="current_search_params" value="" />
<!--    <input type="hidden" name="fields_to_export" id="fields_to_export" value="" />-->
    <input type="hidden" name="labels" id="labels" value="" />
</form>

<div class="one">
    <div class="one_third"><h2 class="grid_cap"></h2></div>
</div>

<div class="spacer"></div>
<table cellpadding="0" cellspacing="0" border="0" class="dyntable sTable2" id="licenses-data-table">
    <thead>
        <tr>
            <th class="head0">Clients Name</th>
            <th class="head1">Created On</th>
<!--            <th class="head0" width="20%">Status</th>-->
        </tr>            
    </thead>
</table>
<div class="hidden">
    <span class="aphabetical_filters">
        <?php
        foreach (range('A', 'Z') as $char) {
            echo '<a href="javascript:;" class="letter_filter">' . $char . '</a> &nbsp;';
        }
        ?>
    </span>
</div>
<script type="text/javascript">

    $("#client_status").multiselect({
        selectedText: "# of # selected"
    });


    /** Datatable code **/
    var popup_dim={
        'correspondence'   :{ search : {h:400,w:460}, result : {h:400,w:460}},
        'setup'             :{ search : {h:880,w:850}, result :{h:800,w:940}}        
    };
    var oTable;
    var active_section='correspondence';
    var active_pagination='';
    var is_fb_open=false;
    var status = 'all';
    $(window).bind('load',function(){        
        $("#client_status").change(function(){
            status = $("#client_status").val();
            if(status == 'null' || status == null){
                status = 'all';
            }
            oTable.fnDestroy();
            init_oTable_initialize(status);
        });
        
        /** Small Plugin to get the pagination info of DataTable **/
        $.fn.dataTableExt.oApi.fnPagingInfo = function ( oSettings )
        {
            return {
                "iStart":         oSettings._iDisplayStart,
                "iEnd":           oSettings.fnDisplayEnd(),
                "iLength":        oSettings._iDisplayLength,
                "iTotal":         oSettings.fnRecordsTotal(),
                "iFilteredTotal": oSettings.fnRecordsDisplay(),
                "iPage":          Math.ceil( oSettings._iDisplayStart / oSettings._iDisplayLength ),
                "iTotalPages":    Math.ceil( oSettings.fnRecordsDisplay() / oSettings._iDisplayLength )
            };
        }

        init_oTable_initialize(status);
        init_alphabetical_filters();
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_client_link();
        init_left_menu_links();
        init_popup_links();
        init_export();
        
    }); 
    
    function init_popup_links(){
        $(document).on("click", "button#pop_prev", function(e){             
            /**
             * Check if this is the first item on the grid 
             * [if yes] Check if this is the first page of the grid 
             * [ If no ] Paginate to the previous page and fire the fnDraw hook to select the last item
             */
            row_index=$('.sTable2 tr').index($('.sTable2 tr.selected'));
            if(row_index==1){
                if(oTable.fnPagingInfo().iPage>0){
                    oTable.fnPageChange('previous');
                    active_pagination='prev';
                }
            }
            else{
                $('.sTable2 tr.selected').removeClass('selected');
                $('.sTable2 tr').eq(row_index-1).addClass('selected');
                setTimeout(function(){ $('.sTable2 tbody tr.selected').find('a.client_link').click() }, 50);
            }
        });
        $(document).on("click", "button#pop_next", function(e){             
            row_index=$('.sTable2 tr').index($('.sTable2 tr.selected'));
            if(row_index==$('.sTable2 tbody tr').size()){
                if(oTable.fnPagingInfo().iPage+1<oTable.fnPagingInfo().iTotalPages){
                    oTable.fnPageChange('next');
                    active_pagination='next';
                }
            }
            else{
                $('.sTable2 tr.selected').removeClass('selected');
                $('.sTable2 tr').eq(row_index+1).addClass('selected');
                setTimeout(function(){ $('.sTable2 tbody tr.selected').find('a.client_link').click() }, 50);
            }
        })
    }

    function init_oTable_initialize(status){
        oTable=$('#licenses-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "bFilter": true,
            "iDisplayLength": 100,
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/clients/ajax-get-clients-list/status/'+status,
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Clients:"
            },
            "aaSorting": [[1,'desc']], // Initial sorting order when page loads
            "fnInitComplete": function (oSettings, json) {                
                $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
            }
        } ); 
    }

    function init_client_link(){
        $(document).on("click", "a.client_link", function(e){             
            if($(".grid_cap").text().indexOf('Search')==0){            
                $('.sTable2 tr.selected').removeClass('selected');
                $(this).parents('tr').addClass('selected');
                v_obj={};
                param_array=$(this).attr('rel').split(",");
                $.each(param_array,function(i,v){
                    v_obj[v.split(":")[0]]=v.split(":")[1];
                });            
                show_result_popup(v_obj);
                console.log(v_obj);
            }
            else{
                window.location.href=site_url+"/admin/clients/view/id/"+$(this).attr('rel');
            }
        });       
    }
    
    function init_export(){
        $(document).on("click", "button.exporter", function(e){             
            show_export_popup();
        });
    }
    
//    function show_export_popup(){
//        $.fancybox({
//            'width'                 : 500,
//            'height'                : 400,
//            'href'                  : site_url+"/admin/clients/export-results/data-type/"+active_section +"/?"+$("#current_search_params").val()  ,    
//            'transitionIn'         : 'none',
//            'transitionOut'        : 'none',
//            'padding'               : 20,
//            'speedIn'               : 0,
//            'ajax'                  :{
//                dataType : 'json',
//                data: 'var1=2'
//            },
//            'type'                  : 'iframe',
//            'changeSpeed'           : 0,            
//            'changeFade'            : 0,
//            'speedOut'              : 0,
//            'overlayColor'          : '#FFF',
//            'titlePosition'        : 'inside'
//        });      
//    }
    
//    function export_result(fields){                
//        $.fancybox.close();
//        $("#fields_to_export").val(fields);
//        window.setTimeout(function(){
//            $("#downloader").attr('action',site_url+"/admin/clients/export-results-excel/")[0].submit();
//        },50);
//    }
    
    function show_result_popup(obj){
        /**
         * obj.v=client
         * obj.m=section . e.g correspondence
         * obj.c=section id. e.g. correspondence id
         */
        $.fancybox({
            'width'                 : popup_dim[obj.m].result.w,
            'height'                : popup_dim[obj.m].result.h,
            'href'                  : site_url+"/admin/clients/show-result-details/id/"+obj.v+"/res-type/"+obj.m+"/cid/"+obj.c,    
            'transitionIn'         : 'none',
            'transitionOut'        : 'none',
            'padding'               : 20,
            'speedIn'               : 0,
            'type'                  : 'iframe',
            'changeSpeed'           : 0,            
            'changeFade'            : 0,
            'speedOut'              : 0,
            'overlayColor'          : '#FFF',
            'titlePosition'        : 'inside',
            'onStart'               :  function(){
                is_fb_open=true;  
            },
            'onClosed'               :  function(){
                is_fb_open=false;  
            },
            'titleFormat'       : function(title, currentArray, currentIndex, currentOpts) {
                return '<button type="Button" id="pop_prev" class="button button_blue">Prev</button>&nbsp; <button id="pop_next" type="Button" class="button button_blue">Next</button>&nbsp; ';
            }
        });   
    }
    
    function init_left_menu_links(){
        $.each([-1,-2],function(i,v){
            //$('ul.leftmenu li').eq(v).hide();
        });
        
        $(document).on("click", "ul.leftmenu li a", function(){ 
            $obj=$(this);
            $.fancybox({
                'width'                 : popup_dim[$obj.attr('rel')].search.w,
                'height'                : popup_dim[$obj.attr('rel')].search.h,
                'href'                  : site_url+"/admin/clients/search-by-cat/type/"+$obj.attr('rel'),    
                'transitionIn'         : 'none',
                'transitionOut'        : 'none',
                'padding'               : 20,
                'overlayColor'          : '#FFF',
                'type'                  : 'iframe',
                'speedIn'               : 100,
                'speedOut'              : 100
            });
            return false;
        });
    }
    
    function fb_resize(w,h){
        $('#fancybox-content').css({ height: h+"px"});
        $('#fancybox-content').css({ width: w+"px"});
        $.fancybox.resize();
    }
    
    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                oTable.fnDraw();                
                return;
            }
        });
    }
    
    function init_alphabetical_filters(){
        $('.letter_filter').on('click',function(){
            oTable.fnFilter($(this).text());
        });
    }
    /** Datatable code **/
    function executeSearch(searchString, grid_caption, url_section){
        grid_caption=grid_caption || "Clients";
        active_section= url_section || 'view';
        $.fancybox.close();    
        $("#current_search_params").val(searchString);
        new_data_table('admin/clients/search-result/?'+searchString,'Search Clients',url_section);
        $('.grid_cap').text(grid_caption);
    }
    
    function new_data_table(new_url,caption,url_section){
        oTable=$('#licenses-data-table').dataTable( {
            "bProcessing": true,
            "bDestroy": true,
            "bFilter": false,
            "bServerSide": true,
            "iDisplayLength": 25,         
            "aLengthMenu": [[10, 25, 50],[10, 25, 50]],
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/'+new_url,
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": caption || ''
            },
            "aaSorting": [[1,'desc']], // Initial sorting order when page loads
            "fnInitComplete": function (oSettings, json) {
                $("#status_filter").hide();
                $('.sTable2').removeAttr('style');
//                if(url_section.toLowerCase() in {'correspondence':'', 'operations':'','clients':'', 'lisc-agreements':'','web-profile':''}){
//                    $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length').append('<button type="button" style="float:right" class="button exporter button_green">Export</button>');
//                } else {
                    $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length');
//                }
                
            },            
            "fnDrawCallback": function() {
                if(active_pagination=="prev"){
                    $('.sTable2 tbody tr').eq(oTable.fnGetNodes().length -1 ).addClass('selected');
                }
                if(active_pagination=="next"){
                    $('.sTable2 tbody tr').eq(0).addClass('selected');
                }
                setTimeout(function(){ $('.sTable2 tbody tr.selected').find('a.client_link').click() }, 50);
            }
        } );
    }
    
</script>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px; 
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
    .sTable2 tbody tr.selected td{
        background-color: #FFFFCC;
    }
    .fancybox-title-inside{
        text-align: left;
    }
    .leftalign{float: left;}
    .rightalign{float: right;}
</style>  
