<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('clients/sidebar-menus.phtml', array('selected' => 'client_vendors', 'id' => $this->client->id));
$this->placeholder('main_side_bar')->captureEnd();
?>

<div class="one">
    <div class="one_third">
       <h2><?php echo $this->client->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Client Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->client->user_status)); ?></h4>       
        </div>
    </div>        
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<div class="spacer"></div>
<table cellpadding="0" cellspacing="0" border="0" class="dyntable" id="licenses-data-table">
    <thead>
        <tr>
            <th class="head0" width="30%">Vendor Name</th>
            <th class="head1" width="30%">Organization Name</th><!-- Applying with-->
            <th class="head0" width="20%">Submitted on</th>
            <th class="head1" width="20%">Status</th>
        </tr>            
    </thead>
</table>
<div class="hidden">
    <span class="aphabetical_filters">
        <?php
        foreach (range('A', 'Z') as $char) {
            echo '<a href="javascript:;" class="letter_filter">' . $char . '</a> &nbsp;';
        }
        ?>
    </span>
</div>
<script type="text/javascript">
    /** Datatable code **/
    var oTable;
    $(window).bind('load',function(){
        oTable=$('#licenses-data-table').dataTable( {
            "bProcessing": false,
            "bServerSide": true,
            "iDisplayLength": 25,            
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/clients/ajax-get-vendors/id/<?php echo $this->client->id; ?>',
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Vendors:"                
            },
            "aaSorting": [[2,'desc']], // Initial sorting order when page loads
            "aoColumnDefs":[
                { "bSortable": true, "aTargets": [ 0 ] }, 
                { "bSortable": false, "aTargets": [ 1 ] }, 
                { "bSortable": true, "aTargets": [ 2 ] }, 
                { "bSortable": true, "aTargets": [ 3 ] }],  // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {
                $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
            }            
        } ); 
        init_alphabetical_filters();
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_vendor_link();
    });    
    
    function init_vendor_link(){
        $(document).on("click", "a.vendor_link", function(){ 
            window.location.href=site_url+"/admin/vendors/view/id/"+$(this).attr('rel');
        });
    }
    
    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                oTable.fnDraw();                
                return;
            }
        });
    }
    
    function init_alphabetical_filters(){
        $('.letter_filter').on('click',function(){
            oTable.fnFilter($(this).text());
        });
    }
    /** Datatable code **/
</script>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px; 
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
</style>   