<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('clients/sidebar-menus.phtml', array('selected' => 'setup', 'id' => $this->client->id));
$this->placeholder('main_side_bar')->captureEnd();
?>

<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/jquery-ui/jquery-ui-timepicker-addon.js"></script>

<div class="one">
    <div class="one_third">
       <h2><?php echo $this->client->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Client Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->client->user_status)); ?></h4>       
        </div>
    </div>        
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<form action="" method="POST" enctype="multipart/form-data" id="client_setup_form">
    <div class="form_container_left">
        <!--<?php echo $this->form->username; ?>-->
        <?php echo $this->form->client_name; ?>
        <?php echo $this->form->greek_letters; ?>
        <?php echo $this->form->description; ?>
        <?php echo $this->form->address1; ?>
        <?php echo $this->form->address2; ?>
        <div class="one_third">
            <?php echo $this->form->city; ?>
        </div>
        <div class="one_third">
            <?php echo $this->form->state; ?>
        </div>
        <div class="one_fifth">            
            <?php echo $this->form->zip_code; ?>
        </div>
        <div class="clear"></div>
        
        <?php echo $this->form->approved_contact; ?>
        <?php echo $this->form->email; ?>
        <?php echo $this->form->agreement_notification_email; ?>
        <?php echo $this->form->url; ?>
        <?php echo $this->form->phone; ?>
        <?php echo $this->form->fax; ?>
    </div>
    <div class="form_container_right">
    	<?php echo $this->form->user_code;?>
    	<!--<?php echo $this->form->password; ?>-->
        <?php echo $this->form->def_ren_fee; ?>
        <?php echo $this->form->def_late_fee; ?>
        <!--<?php echo $this->form->royalty; ?>-->
        <?php echo $this->form->org_type; ?>
        <?php echo $this->form->founding_year; ?>
        <?php echo $this->form->num_alumni; ?>
        <?php echo $this->form->num_undergrads; ?>
        <?php echo $this->form->num_alumni_chapters; ?>
        <?php echo $this->form->total_ug_chapters; ?>
        <?php echo $this->form->grant_of_lic; ?>                
    </div>
    <div class="spacer clear"></div>
    <button type="submit" class="button button_black detail_button">Submit</button>
</form>
<style type="text/css">
    #city, #state, #zip_code{
        width:110px;
    }
    div.jGrowl div.jGrowl-notification
    {
        color:#000000;
        background-color:#A79269;
    }
    #org_type{
        width:100%; height: 30px;
        background-color: #ffffff !important;
    }        
</style>
<script type="text/javascript">
    validated=false;    
    $(function(){        
        //$("#founding_year").datetimepicker({
            showHour:false,showMinute:false,showSecond:false,timeText:"",timeFormat: '',currentText:"Today"
        });
        /*$("#client_setup_form").on('submit',function(){
            $form=$(this);
            if(!validated){
                $.ajax({
                    type: 'post',
                    data : $("#client_setup_form").serialize(),
                    dataType: 'json',
                    success: function(e){
                        $valid=$.isEmptyObject(e) ? true : false;
                        if(!$valid){
                            $form.find('.error').removeClass('error');
                            $form.find('.js_gen_errors').remove();
                            for(var i in e){
                                $.map( e[i], function(val, k) {
                                    $('input[name='+i+']').addClass('error')
                                    .after('<ul class="errors js_gen_errors"><li>'+val+'</li></ul>');
                                });                            
                            }
                            return false;
                        }else{
                            validated=true;
                            $form.find('.error').removeClass('error');
                            $form.find('.js_gen_errors').remove();
                            $form[0].submit();
                            return true;
                        }
                    }
                });
                return false;
            }
        })*/
    });
</script>
