<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('clients/sidebar-menus.phtml',array('selected'=>'web_profile','id'=>$this->client->id));
$this->placeholder('main_side_bar')->captureEnd();
?>

<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/jquery-ui/jquery-ui-timepicker-addon.js"></script>

<div class="one">
    <div class="one_third">
       <h2><?php echo $this->client->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Client Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->client->user_status)); ?></h4>       
        </div>
    </div>        
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<form method="POST" id="<?php echo $this->form->getName(); ?>" enctype="multipart/form-data">
    <div class="form_container_left">
        <?php echo $this->form->organization_name; ?>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->greek_name; ?>
    </div>
<!--    <div class="clear"></div>
    <div class="form_container_left">
        <?php echo $this->form->organization_symbol; ?>
        The optimal size of the symbol should be ZZZpx X ZZZpx.
        <?php
        if($this->symbol!=''){
        ?>
            &nbsp;&nbsp;<a class="example1" href="<?php echo $this->baseUrl("assets/files/client_profile/".$this->symbol); ?>">View</a>
        <?php
        }
        ?>
    </div>-->
    <div class="form_container_right">
        
    </div>
    <div class="clear"></div>
    <div class="form_container_left">
        <?php echo $this->form->address_line1; ?>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->phone1; ?>
    </div>
    <div class="clear"></div>
    <div class="form_container_left">
        <?php echo $this->form->address_line2; ?>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->phone2; ?>
    </div>
    <div class="clear"></div>
    <div class="form_container_left">
        <div class="one_third">
            <?php echo $this->form->city; ?>
        </div>
        <div class="one_third">
            <?php echo $this->form->state; ?>
        </div>
        <div class="one_fifth">
            <?php echo $this->form->zip; ?>
        </div>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->fax; ?>
    </div>
    <div class="clear"></div>
    <div class="form_container_left">
        <?php echo $this->form->email; ?>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->webpage; ?>
    </div>
    <div class="clear"></div>

    <hr size="1" />
    <div class="spacer"></div>
    <div class="form_container_left">
        <?php echo $this->form->greek_org_type; ?>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->greek_number_of_colg_chapters;?>
    </div>
    <div class="clear"></div>

    <div class="form_container_left">
        <?php echo $this->form->greek_founding_year; ?>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->greek_number_of_alumni_chapters; ?>
    </div>
<!--    <div class="form_container_left">
        <?php echo $this->form->founding_address_line1; ?>
    </div>-->
<div class="clear"></div>
    <div class="form_container_left">
        <?php echo $this->form->greek_number_of_undergrads; ?>
    </div>
<!--    <div class="clear"></div>
    <div class="form_container_left">
        <?php echo $this->form->founding_address_line2; ?>
    </div>-->
    <div class="form_container_right">
        <?php echo $this->form->greek_number_of_alumni; ?>
    </div>
<!--    <div class="clear"></div>
    <div class="form_container_left">
        <div class="one_third">
            <?php echo $this->form->founding_city; ?>
        </div>
        <div class="one_third">
            <?php echo $this->form->founding_state; ?>
        </div>
        <div class="one_fifth">
            <?php echo $this->form->zip; ?>
        </div>
        <div class="clear"></div>
    </div>-->
<div class="clear"></div>
    <div class="form_container_left">
        <div class="one_third">
        <?php echo $this->form->headquarters_city; ?>
            </div>
        <div class="one_third">
            <?php echo $this->form->headquarters_state; ?>
        </div>
    </div>
    <div class="spacer"></div>
        <button type="submit" class="button button_black detail_button">Submit</button>
</form>
<style type="text/css">
    #city,#state,#zip,#sal,#founding_city,#founding_state, #headquarters_city, #headquarters_state{
        width:110px;
    }
    #first_name{
        width:250px;
    }
    #greek_org_type{
        width:100%; height: 30px;
    }
    #organization_logo, #organization_symbol{width: 150px; height: 25px;}
    #greek_org_type{
        background-color: #ffffff !important;
    }
    .jGrowl-notification{
        background-color: #917C54 !important;
    }
</style>
<script type="text/javascript">
    
    $(function(){

        $("a.example1").fancybox();

        var cur_year = "<?php echo date('Y') ?>";
        var cur_month = "<?php echo date('m') - 1 ?>";
        var cur_day = "<?php echo date('d') ?>";
        $("#greek_founding_year").datetimepicker({
            minDate: new Date(cur_year, cur_month, cur_day, 8, 30),
            maxDate: new Date(2030, 11, 31, 17, 30), showHour:false,showMinute:false,showSecond:false,timeText:"",timeFormat: '',currentText:"Today"
        });
        
    });
</script>
