<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('vendors/vendor-sidebar-menus.phtml', array('selected' => 'contact', 'id' => $this->vendor->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<div class="one">
    <div class="one_third">
        <h2><?php echo $this->vendor->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Vendor Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->vendor->user_status)); ?></h4>
        </div>
    </div>
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<form action="" method="POST" enctype="multipart/form-data" id="<?php echo $this->form->getName(); ?>">
    <?php echo $this->form->editContact; ?>
    <div class="form_container_left">
        <?php echo $this->form->username; ?>
        <?php echo $this->form->email; ?>
        <?php echo $this->form->organization_name; ?>
        <?php echo $this->form->address_line_1; ?>
        <?php echo $this->form->address_line_2; ?>
        <div class="one_third">
            <?php echo $this->form->city; ?>
        </div>
        <div class="one_third">
            <?php echo $this->form->state; ?>
        </div>
        <div class="one_fifth">
            <?php echo $this->form->zip; ?>
        </div><div class="clear"></div>
        <?php echo $this->form->company_email; ?>
       <div class="clear"></div>
    </div>
    <div class="form_container_right">
        <?php echo $this->form->vendor_number; ?>
        <?php echo $this->form->user_password; ?>
        <?php echo $this->form->phone_1; ?>
        <?php echo $this->form->phone_2; ?>
        <?php echo $this->form->fax; ?>
        <?php echo $this->form->web_page; ?>
    </div>
    <div class="clear"></div>

    <div class="form_container_left">
        <button type="button" id="btn_edit" class="button button_black detail_button">Edit</button>
        <button type="submit" id="submitEdit" class="button button_black detail_button extSpace3">Submit</button>
    </div>
    <div class="clear"></div>

    <?php echo $this->form->v_addNew; ?>
    <div>
        <div class="spacer"></div>
        <h2 class="contact">Contacts</h2>
        <hr size="1" noshade />
        <div class="spacer"></div>
        <table cellspacing="0" cellpadding="0" border="1" id="licenses-data-table" class="dyntable dataTable" aria-describedby="licenses-data-table_info">
            <tr class="tr_heading">
                <td width="8%" class="td_bkg1">Sal.</td>
                <td width="10%" class="td_bkg2">First</td>
                <td width="10%" class="td_bkg1">Last</td>
                <td width="13%" class="td_bkg2">Job Title</td>
                <td width="10%" class="td_bkg1">Work Phone</td>
                <td width="10%" class="td_bkg2">Mobile</td>
                <td width="13%" class="td_bkg1">Email</td>
                <td width="12%" class="td_bkg2">Contact Type</td>
                <td width="8%" class="td_bkg1">Action</td>
            </tr>
            <?php
            if(count($this->userOperation)>0){
                foreach($this->userOperation as $contact){
                    echo "<tr>";
                    echo "<td>".$contact->sal."</td>";
                    echo "<td>".$contact->first_name."</td>";
                    echo "<td>".$contact->last_name."</td>";
                    echo "<td>".$contact->title."</td>";
                    echo "<td>".$contact->phone."</td>";
                    echo "<td>".$contact->mobile."</td>";
                    echo "<td>".$contact->email."</td>";
                    echo "<td>".$contact->contact_type."</td>";
                    echo '<td>
                                <a href="javascript:;" rel="'. $contact->id .'" class="edit-contact">View & Edit</a>
                                | <a href="' . $this->baseUrl("admin/vendors/delete-contact/id/" . $contact->id."/vendor_id/".$this->vendor->id) . '" class="delete-contact">Delete</a>
                        </td>';
                    echo "</tr>";
                }
            }
            ?>
            <tr id="add_new_contact">
                <td><?php echo $this->form->v_sal; ?></td>
                <td><?php echo $this->form->v_first_name; ?></td>
                <td><?php echo $this->form->v_last_name; ?></td>
                <td><?php echo $this->form->v_title; ?></td>
                <td><?php echo $this->form->v_phone; ?></td>
                <td><?php echo $this->form->v_mobile; ?></td>
                <td><?php echo $this->form->v_email; ?></td>
                <td><?php echo $this->form->v_contact_type; ?></td>
                <td>&nbsp;</td>
            </tr>
            <tr id="validate_new_contact">
                <td id="validate_sal">&nbsp;</td>
                <td id="validate_first_name">&nbsp;</td>
                <td id="validate_last_name">&nbsp;</td>
                <td id="validate_title">&nbsp;</td>
                <td id="validate_phone">&nbsp;</td>
 <!--               <td id="validate_phone_ext">&nbsp;</td> -->
                <td id="validate_mobile">&nbsp;</td>
 <!--               <td id="validate_fax">&nbsp;</td>-->
                <td id="validate_email">&nbsp;</td>
                <td id="validate_contact_type">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>

        </table>
        <div class="btn2">
            <button type="button" id="btn_add_new" class="button button_black detail_button">Add New</button>
            <button type="submit" id="submitAddContact" class="button button_black detail_button">Submit</button>
            <div class="clear"></div>
        </div>
    </div>
</form>

<style type="text/css">
    #city,#state,#zip,#sal{
        width:110px;
    }
    #first_name{
        width:250px;
    }
    #v_phone_ext{
        width: 30px !important;
    }
    #validate_new_contact{font-size: 11px; color: red;}
</style>

<script type="text/javascript">

    $(document).ready(function() {
        var flag = true;

        if(('<?php echo $this->success; ?>') !=""){
            $.jGrowl('<?php echo $this->success; ?>');
        }

        $("input.text, input.password, select#state").addClass('desable').prop('disabled', true);
        $("button#submitEdit, tr#add_new_contact, tr#validate_new_contact, button#submitAddContact").hide();

        <?php
        if($this->editContact=="1"){?>
            $("input.text, input.password, select#state").removeClass('desable').addClass('enable').prop('disabled', false);
            $("button#btn_edit").text("Cancel");
            $("button#submitEdit").show();
        <?php } ?>

        <?php
        if($this->v_addNew=="1"){?>
            $("tr#add_new_contact, button#submitAddContact").show();
            $("button#btn_add_new").text("Cancel");
        <?php } ?>

        $("button#btn_edit").toggle(function(){
            $(this).text("Cancel");
            $("button#submitEdit").show();
            $("input.text, input.password, select#state").removeClass('desable').addClass('enable').prop('disabled', false);
            hide_new_contact();
        },
        function(){
            $(this).text("Edit");
            $("button#submitEdit").hide();
            $("input.text, input.password, select#state").removeClass('enable').addClass('desable').prop('disabled', true);
        });

        $("button#submitEdit").click(function(){
            //return false;
            $("#editContact").val("1");
            $("input.elWidth, select.elWidth").prop('disabled', true);
            $("#contact_form").submit();
        });

        $("button#btn_add_new").toggle(function(){
            $("input.elWidth, select.elWidth").prop('disabled', false);
            $(this).text("Cancel");
            $("button#submitAddContact").show();
            $("tr#add_new_contact").show();
            $("tr#validate_new_contact").show();
            $("#v_sal").focus();
            hide_contact();
        },
        function(){
            $("input.elWidth, select.elWidth").prop('disabled', true);
            $(this).text("Add New");
            $("button#submitAddContact").hide();
            $("tr#add_new_contact").hide();
            $("tr#validate_new_contact").hide();
        });

        $("button#submitAddContact").click(function(){
            //return false;
            $("#v_addNew").val("1");
            $("#contact_form").submit();
        });

    });

    function hide_contact(){
        $("button#btn_edit").text("Edit");
        $("button#submitEdit").hide();
        $("input.text").removeClass('enable').addClass('desable').prop('disabled', true);
    }

    function hide_new_contact(){
        $("button#btn_add_new").text("Add New");
        $("button#submitAddContact").hide();
        $("tr#add_new_contact").hide();
        $("input.elWidth").prop('disabled', true);
    }

    jQuery(function($){
        //for edit contact
        $(document).on('click', 'a.edit-contact', function(){
            var link = site_url+"/admin/vendors/edit-contact/id/"+ $(this).attr('rel')+"/vendor_id/"+'<?php echo $this->vendor->id; ?>';
            loadPopView(link);
            return false;
        });
    });

    function loadPopView(thisItem){
        $.fancybox({
            'width'                 : '68%',
            'height'                : '55%',
            'href'                  : thisItem,
            'autoScale'             : true,
            'transitionIn'          : 'none',
            'transitionOut'         : 'none',
            'type'                  : 'iframe',
            'transitionIn'     : 'elastic',
            'transitionOut'     : 'elastic',
            'speedIn'      : 100,
            'speedOut'      : 100,
            'overlayShow'     : false,
            'onClosed'              : function() {
               // window.location = $obj.attr('param');
            }
        });
    }

    function execute_parent(msg){
        $.fancybox.close();
        $.jGrowl(msg);
        location.reload();
    }

    var REG_EXP = /\(?([0-9]{3})\)?([ ]?)([0-9]{3})([-]?)([0-9]{4})/;
    $(document).on('blur', '#v_phone', function(){
        if($('#v_phone').val() != ""){
            if(REG_EXP.test($('#v_phone').val()) == false){
                $('#validate_phone').html('Format must be (xxx) xxx-xxxx');
            }
            else{
                $('#validate_phone').html('');
            }
        }
        else{
            $('#validate_phone').html('');
        }
    });

    $(document).on('blur', '#v_mobile', function(){
        if($('#v_mobile').val() != ""){
            if(REG_EXP.test($('#v_mobile').val()) == false){
                $('#validate_mobile').html('Format must be (xxx) xxx-xxxx');
            }
            else{
                $('#validate_mobile').html('');
            }
        }
        else{
            $('#validate_mobile').html('');
        }
    });


    $(document).on('blur', '#v_fax', function(){
        if($('#v_fax').val() != ""){
            if(REG_EXP.test($('#v_fax').val()) == false){
                $('#validate_fax').html('Format must be (xxx) xxx-xxxx');
            }
            else{
                $('#validate_fax').html('');
            }
        }
        else{
            $('#validate_fax').html('');
        }
    });
</script>

<script type="text/javascript">
    $(window).bind('load', function(){
        event_functions._initialize();

        $(document).on('click', 'a.delete-contact', event_functions.delete_contact);
    });

    event_functions = {
        _initialize : function(){

        },
        delete_contact:function(){
            if(confirm("Are you sure to delete this contact ?")){
                return true;
            }
            return false;
        }
    }
</script>