<div id="view-content">
    <h2>Vendor Correspondence</h2>
    <div class="spacer clear"></div>
    <hr size="1" noshade />
    <div class="spacer clear"></div>

    <div class="one">
	<h3>Recieved:</h3>
        <?php echo $this->correspondence->update_date->format('Y-m-d H:i:s'); ?>
        <h3>Subject:</h3>
        <?php echo html_entity_decode($this->correspondence->subject); ?>
        <div class="spacer clear"></div>
        <h3>Note:</h3>
        <pre><?php echo strip_tags(html_entity_decode($this->correspondence->note), "<br/><br /><br><br >"); ?></pre>
    </div>
</div>

<style type="text/css">
    pre {
    white-space: -moz-pre-wrap; /* Mozilla, supported since 1999 */
    white-space: -pre-wrap; /* Opera */
    white-space: -o-pre-wrap; /* Opera */
    white-space: pre-wrap; /* CSS3 - Text module (Candidate Recommendation) http://www.w3.org/TR/css3-text/#white-space */
    word-wrap: break-word; /* IE 5.5+ */
    font-family: DroidSansRegular, "Segoe UI", "Lucida Sans Unicode", "Lucida Grande", sans-serif;
font-size: 13px;
}
</style>
