<script type="text/javascript" src="<?php echo $this->baseUrl("assets"); ?>/js/tiny_mce/tiny_mce.js"></script>
<div class="one" id="view-content">       
    <h2>Review Registrant</h2>
    <hr size="1"/>
    <div class="spacer clear"></div>
    
    <form action="" enctype="multipart/form-data" method="POST" id="decline_form">        
        <div class="one" style="font-size: 12px; font-weight: bold;">           
            <?php echo $this->form->decline_reason; ?>
        </div>
        <div class="spacer clear"></div>
        <div class="one">
            <button type="button" class="button button_blue" id="submit_button" >Submit</button>
        </div>
    </form>    
    <div class="spacer clear"></div> 
    
    <div style="display: none;" id="loader_div">
        <div id="loader"><img src="<?php echo $this->baseUrl("assets/images/loading.gif"); ?>" /></div>
    </div>     
   
</div>       
<script type="text/javascript">
 $(document).ready( function($) {    
    if('<?php echo $this->msg; ?>' !=""){      
        window.parent.execute_refresh('<?php echo $this->msg; ?>');
    }    
 });
 
 $(document).on('click', '#submit_button', function(){
     $("#loader_div").show();
     $("#decline_form").submit();
 });
</script>
<script type="text/javascript">
    tinyMCE.init({
        mode : "textareas",
        elements : "decline_reason",
        theme : "advanced",
        height: "300",
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,forecolor,backcolor,hr,removeformat,visualaid,|,sub,sup,|,charmap",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_path : false,
        theme_advanced_font_sizes: "8px, 9px, 10px, 11px, 12px,14px,16px,18px,20px,24px,28px,36px,44px",
        font_size_style_values : "13px, 14px,16px,18px,20px",
        content_css : "<?php echo $this->baseUrl("assets"); ?>/css/custom_content.css",
        force_br_newlines : true,
        force_p_newlines : false,
        forced_root_block : "",
        theme_advanced_resizing : true,
        skin : "o2k7",
        skin_variant : "silver"
    });
</script>
