<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('vendors/vendor-sidebar-menus.phtml',array('selected'=>'docs','id'=>$this->vendor->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<?php echo $this->form;?>
<script type="text/javascript">
    $(function(){
        $("#docs_form").on('submit',function(){
            if($.trim($("#file_name").val())==""){
                alert('Please write Documents Name');
                $("#file_name")[0].focus();
            }else{
                $.ajax({
                    url:site_url+'/admin/vendors/ajax-save-docs/',
                    dataType:'json',
                    data : $('#docs_form').serialize()+'&vid='+<?php echo $this->vendor->id; ?>,
                    type:'post',
                    success:function(e){                   
                        <?php if ($this->is_popup == "yes"): ?>
                            window.parent.$.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                        <?php else: ?>
                            $.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                        <?php endif; ?>
                        if(e.code=='success'){
                            oTable.fnDraw();
                            $('#docs_form')[0].reset();
                        }
                        $('#file_name').val('');
                    }
                });
            }
            return false;            
        });
<?php if (sizeof($this->docs)):
        if (!is_null($this->docs->update_date)) {
            $update_date = ( (int) $this->docs->update_date->format("Y") > 0 ? $this->docs->update_date->format("M d, Y H:i A") : 'N/A');
        } else {
            $update_date = 'N/A';
        }  
?>        
            $('label[for=file_name]').prepend('Vendor : <b><?php echo $this->vendor->organization_name; ?></b><br />Date : <?php echo $update_date; ?><hr size="1" />');
<?php endif; ?>
    });
</script>
<style type="text/css">
    .text,.textarea{
        width:420px;
    }
</style>