<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('vendors/vendor-sidebar-menus.phtml', array('selected' => 'docs', 'id' => $this->vendor->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<div class="one">
    <div class="one_third">
        <h2><?php echo $this->vendor->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Vendor Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->vendor->user_status)); ?></h4>       
        </div>
    </div>      
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<?php //echo $this->partial('vendors/docs-form-partial.phtml',array('form'=>$this->form,'vendor'=>$this->vendor));?>
<form  action="" method="POST" enctype="multipart/form-data" id="<?php echo $this->form->getName(); ?>"> 
    <input type="hidden" name="vendor_id" value="<?php echo $this->vendor->id; ?>" />    
    <div class="one_half">
        <div class="one_half">
            <?php echo $this->form->file_name; ?>
        </div>
        <div class="spacer"></div>
        <div class="one_half">
            <?php echo $this->form->upload_doc; ?>
        </div>
        <div class="spacer"></div>
        <div class="one_third">
            <button type="submit" class="button button_black detail_button">Save</button>
        </div>
    </div>
</form>

<div class="spacer"></div>
<div class="spacer"></div>

<table cellpadding="0" cellspacing="0" border="0" class="dyntable" id="docs-data-table">
    <thead>
        <tr>
            <th class="head1" width="160">Date</th>
            <th class="head0" width="20%">Type</th>
            <th class="head1">Document Name</th>
            <th class="head0" width="150">Action</th>
        </tr>            
    </thead>
</table>

<script type="text/javascript">
      
    /** Datatable code **/
    var oTable;
    $(window).bind('load',function(){
        oTable=$('#docs-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "iDisplayLength": 10,            
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/vendors/ajax-get-docs/id/<?php echo $this->vendor->id; ?>',
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Docs:"                
            },
            "aaSorting": [[0,'desc']], // Initial sorting order when page loads
            "aoColumnDefs":[
                { "bSortable": true, "aTargets": [ 0 ] },
                { "bSortable": true, "aTargets": [ 1 ] },
                { "bSortable": false, "aTargets": [ 2 ] },
                { "bSortable": false, "aTargets": [ 3 ] }],  // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {
                $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
            },
            fnDrawCallback:function(){
                init_vendor_link();
            }            
        } ); 
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_vendor_link();
        init_download_documents_link();  
    });    

    function init_vendor_link(){
        $("a.vendor_docs_link").each(function(){ 
            $(this).qtip(
            {
                content: {
                    text: 'Loading..',      
                    title: {
                        text: 'Documents Details', // Give the tooltip a title using each elements text
                        button: false
                    },
                    ajax: {
                        url: site_url+'/admin/vendors/ajax-get-docs-details/docs-id/'+$(this).attr('rel')
                    }
                },
                position: {
                    my: 'center', // ...at the center of the viewport
                    at: 'center',
                    target: $(window),
                    viewport: $(window),
                    effect: false
                    
                },
                show: {
                    event: 'click', 
                    solo: true, 
                    modal: true 
                },
                hide: 'unfocus',
                style: {
                    width:'800px',
                    classes : 'ui-tooltip-shadow ui-tooltip-light ui-tooltip-rounded'
                }
            })
            .click(function(event) { event.preventDefault(); });
        });
    }

    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                return;
            }
        });
    }
    
    function init_download_documents_link(){
        $(document).on("click", "a.download_docs", function(){          
            window.location.href = site_url+"/admin/vendors/download-documents/file/"+$(this).attr('rel');            
            return false;
        });
    }    
    
    function init_alphabetical_filters(){
        $('.letter_filter').on('click',function(){
            oTable.fnFilter($(this).text());
        });
    }
    /** Datatable code **/
    
    $(function(){
        $(document).on('click', 'a.delete_docs', function(){
            if(confirm('Are you sure to delete this document?')){
                $docs_id=$(this).attr('rel').split("-")[1];
                $.ajax({
                    url:site_url+'/admin/vendors/ajax-delete-docs/',
                    dataType:'json',
                    data : 'docs_id='+$docs_id+'&vid='+<?php echo $this->vendor->id; ?>,
                    type:'post',
                    success:function(e){
                        $.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                        if(e.code=='success'){
                            oTable.fnDraw();
                        }
                    }
                });
            }
            return false;
        });
    })
    
    $(function(){                                 
        $('#docs_form').validate({
            errorClass : 'error',
            rules:{
                file_name : {'required' : true}  ,
                upload_doc : {'required' : true}                
            },
            messages:{
                file_name : {'required' : "<br />Please enter document name"},
                upload_doc : {'required' : "<br />Please upload a Document"}                
            },
            submitHandler:function(form){
                form.submit(
                /////////////////////
                //                  $.ajax({                        
                //                    url:site_url+'/admin/vendors/ajax-save-docs/',
                //                    dataType:'json',
                //                    data : $('#docs_form').serialize()+'&vid='+<?php //echo $this->vendor->id;  ?>,
                //                    type:'post',
                //                    success:function(e){                   
                //                        <?php //if ($this->is_popup == "yes"):  ?>
                //                            window.parent.$.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                //                        <?php //else:  ?>
                //                            $.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                //                        <?php //endif;  ?>
                //                        if(e.code=='success'){
                //                            oTable.fnDraw();
                //                            $('#docs_form')[0].reset();
                //                        }
                //                        $('#file_name').val('');
                //                    }
                //                })
                /////////////////////////
            );
            }
        })
    });

    
</script>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px; 
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
    .ui-tooltip-content{
        font-size:110%;
        line-height: 150%
    }
    .ui-tooltip, .qtip{
        max-width: 500px; 
    }
    #file_name{
        width: 500px;
    }
</style>   
