<?php
//print_r($this->imageLink);
//echo $this->baseUrl('assets/files/samples/products/'. $this->imageLin)?>
<style type="text/css">
    .ui-autocomplete-loading
       {
            
      }
      .left_div{width:20%; float: left;}
      .right_div{width:80%; font-size: 13px; float: left;}

</style>

<div class="ui-autocomplete-loading" style='float:left; width: 100%; height: 100%;'>
    <img src="<?php echo $this->baseUrl('assets/files/samples/products/'. $this->imageLink)?>">
</div>
