<?php echo $this->partial('vendors/invoice_menus.phtml'); ?>
<div class="spacer"></div>
<div class="one_half">
    <?php
    $current_year = Date("Y");
    
    $years = range($current_year + 1, $current_year - 5);
 //   echo $current_year;
    
    if (isset($this->yr)){
    	$current_year = substr($this->yr, 0, 4);
    	
   // 	echo " " . substr($this->yr, 0, 4) . " ";
  		
    	
    }
    
    $year_dropdown_vals = array();
    foreach ($years as $year) {
        $year_dropdown_vals[($year - 1) . "-" . substr($year, 2)] = ($year - 1) . "-" . substr($year, 2);
    }
    echo $this->formLabel("fiscal_year", "Fiscal Year ");
    echo $this->formSelect("fiscal_year", "", array('class' => 'filters'), $year_dropdown_vals);
    echo str_repeat("&nbsp;", 2);
    
    $cuttoff_day = BL_AMC::$quarters[BL_AMC::getCurrentQarter()]['end'] + BL_AMC::GRACE;        
    ?>

<div class="spacer"></div><br />
    <?php foreach (BL_AMC::$quarters as $num => $quarter): ?>
        <h3>Q<?php echo $num; ?> &nbsp; ( <?php
    $date1 = DateTime::createFromFormat('Y z', "{$current_year} {$quarter['start']}");
    echo $date1->format("F d");
    echo " - ";
    $date2 = DateTime::createFromFormat('Y z', "{$current_year} {$quarter['end']}");
    echo $date2->format("F d");
        ?> )
        </h3><hr size="1" noshade />
        Cut-off date for submitting royalty reports : 
        <?php
        $cuttoff_end_day = $quarter['end'] + BL_AMC::GRACE;
        $cuttoff_date = DateTime::createFromFormat('Y z', "{$current_year} {$cuttoff_end_day}");                
        echo "<b>".$cuttoff_date->format("F d")."</b>";                                      
        
        
        if((date('z') <= $cuttoff_day) && (BL_AMC::isInRange(date('z'), $quarter['start'], $quarter['end']))){            
        ?>
        <div class="spacer"></div>
        <div class="">
            Late fee invoices generated on: &nbsp;<b>N/A</b>           
        </div>        
        <?php } ?>
        <div class="spacer"></div>     
                
        <?php
        if((date('z') < $cuttoff_day) && ($cuttoff_end_day < $cuttoff_day)){
        ?>
        <div class="spacer"></div>
        <div class="">
            Late fee invoices generated on: &nbsp;<b>N/A</b>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  
            <a href="javascript:;" class="iconlink2" id="view_late_fee" rel="<?php echo $num; ?>"><span>View Late Fee Invoices</span></a>
        </div>        
        <?php    
        }
        ?>
        
        <?php
        if((date('z') > $cuttoff_end_day)){
        ?>
        <div class="spacer"></div>
        <div class="">
            Late fee invoices generated on: &nbsp;<b>N/A</b>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  
            <span><a href="javascript:;" class="iconlink2" id="generate" rel="<?php echo $num; ?>">Generate Now</a></span>
        </div>        
        <?php         
        }
        ?>
        
    <?php endforeach; ?>

</div>

<div id="dialog-preview-notified" class="notified-class" title="" style="display:none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin: 0 7px 20px 0;"></span></p>
</div>

<div id="dialog-progress-bar" class="notified-class" title="" style="display:none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin: 0 7px 20px 0;"></span></p>
</div>

<div id="dialog-success-bar" class="notified-class" title="" style="display:none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin: 0 7px 20px 0;"></span></p>
</div>

<script type="text/javascript">

	$(document).ready(function(){

		var year = 'option[value="<?php echo (isset($this->yr))? $this->yr:"";?>"]';

		console.log("ready");
		

		$(year).prop('selected', true);
	});
        
    $(document).on('click', '#view_late_fee', function(){
        document.location = site_url+"/admin/vendors/invoice";       
    });
    
    $(document).on('click', '#generate', function(){
		var quarter = $(this).attr('rel');
		var year = $("option:selected").attr('value');
    	
		var html = 'You are about to generate late fees for quarter ' + quarter + '. Are you sure you want to coninue?';

		$("#dialog-preview-notified").html(html);
		$("#dialog-preview-notified").dialog({
				resizable: false,
				height: 'auto',
				width: 640,
				modal: true,
				title: "Confirmation",
				buttons:{
					"Continue": function(){
						$(this).dialog("close");

						$.ajax({
							url: site_url+"/admin/vendors/invoice-generate-late-fees/quarter/" + quarter + "/year/" + year,
							type: "POST",
							beforeSend: function(){
								var html='<div style="width: 220px; margin: 0 auto;"><img src="'+site_url+'/assets/images/ajax-loader.gif" /></div>';
								html += '<div style="width: 312px; margin: 0 auto;">Generating late fees...</div>';

								$("#dialog-progress-bar").html(html);
								$("#dialog-progress-bar").dialog({
									resizable: false,
									height: 'auto',
									width: 640,
									modal: true,
									title: "Processing"
								});
							},
							complete: function(){
								$("#dialog-progress-bar").dialog("close");
							},
							success: function(msg){
								var html = "All late fees have been generated.";
								$("#dialog-success-bar").html(html);
								$("#dialog-success-bar").dialog({
									resizable:false,
									height:'auto',
									width: 640,
									modal: true,
									title: "View invoices",
									buttons:{
										"View late fee invoices": function(){
											$(this).dialog("close");
											window.location.href = site_url+"/admin/vendors/invoice";
										},
										"Cancel": function(){
											$(this).dialog("close");
										}
									}
								});
							}
						});
					},
					"Cancel": function(){
						$(this).dialog("close");
					}
				}
			});

               
    });

    $(document).on('change', '#fiscal_year', function(){
		var text = $('#fiscal_year').find(":selected").val();

		console.log("changed " + text);
	        
		document.location = site_url+"/admin/vendors/invoice-generate-late-fees/year/" + text;
    });

</script>