<?php
//$this->placeholder('main_side_bar')->captureStart();
//echo $this->partial('vendors/vendor-sidebar-menus.phtml');
//$this->placeholder('main_side_bar')->captureEnd();
?>
<?php echo $this->partial('vendors/invoice_menus.phtml'); ?>
<div class="clear"></div>
<div class="spacer"></div>
<div class="one">
    <form id="invoice_filter">
        <?php
        $current_year = Date("Y");
        $years = range($current_year + 1, $current_year - 5);
        $year_dropdown_vals = array();
        $year_dropdown_vals['All']='All';
        foreach ($years as $year) {
            $year_dropdown_vals[($year - 1) . "-" . substr($year, 2)] = ($year - 1) . "-" . substr($year, 2);
        }

        $year_selected = $current_year."-".($current_year+1);
        echo $this->formLabel("fiscal_year", "Fiscal Year ");
        echo $this->formSelect("fiscal_year", "$year_selected", array('class' => 'filters'), $year_dropdown_vals);
        echo str_repeat("&nbsp;", 2);

        $vendor_status = BL_AMC::parseYAML(APPLICATION_PATH . '/configs/vendor_status_for_invoice_search.yml');
        echo $this->formLabel("vendor_status", "Vendor Status ");
        echo $this->formSelect("vendor_status", 'current', array('class' => 'filters'), $vendor_status);

        echo str_repeat("&nbsp;", 2);
        $inv_types = BL_AMC::parseYAML(APPLICATION_PATH . '/configs/invoice_types.yml');
        echo $this->formLabel("invoice_type", "Invoice Type ");
        echo $this->formSelect("invoice_type", '', array('class' => 'filters'), $inv_types);

        echo str_repeat("&nbsp;", 2);
        echo $this->formLabel("quarter", "Quarter ");
        echo $this->formSelect("quarter", BL_AMC::getCurrentQarter(), array('class' => 'filters'), array("" => "All", "1" => "Q1", "2" => "Q2", "3" => "Q3", "4" => "Q4"));

        echo str_repeat("&nbsp;", 2);
        $inv_statuses = BL_AMC::parseYAML(APPLICATION_PATH . '/configs/invoice_status.yml');
        
        if ($this->user->account_type != 1){
        	unset($inv_statuses['Closed']);
        }
        
        echo $this->formLabel("invoice_status", "Invoice Status ");
        echo $this->formSelect("invoice_status", 'open', array('class' => 'filters'), $inv_statuses);

        echo str_repeat("&nbsp;", 2);
        $payment_statuses = BL_AMC::parseYAML(APPLICATION_PATH . '/configs/payment_status.yml');
        echo $this->formLabel("payment_status", "Payment Status ");
        echo $this->formSelect("payment_status", 'due', array('class' => 'filters'), $payment_statuses);
        ?>
    </form>
    <div class="spacer"></div>
    <div class="" style="width: 100%">
        <table cellpadding="0" cellspacing="0" border="0" style="width:100%" class="dyntable" id="invoices-data-table">
            <thead>
                <tr>
                    <th class="head0" width="20%">Vendor Name</th>
                    <th class="head1" width="13%">Vendor Status</th>
                    <th class="head0" width="15%">Invoice Number</th>
                    <th class="head1" width="15%">Invoice Date</th>
                    <th class="head0" width="12%">Invoice Amount</th>
                    <th class="head1" width="13%">Amount Paid</th>
                    <th class="head0" width="12%">Amount Due</th>
                    <th class="head1" width="12%">Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<style type="text/css">
    div.jGrowl div.jGrowl-notification {
        color: #000000;
        background-color: #A79269;
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
    
    .money{ text-align: right};
    
    
</style>

<script type="text/javascript">

    var oTable;
    $(window).bind('load',function(){
        vendor_invoice.init_oTable_initialize();
        $('.filters').on('change',vendor_invoice.init_oTable_initialize);
//        $('a.lineitems_link').on('click', vendor_lineitems.show_invoice_lineitems);
        init_payment_link();
        init_lineitems_link();
    })

    vendor_invoice={
        init_oTable_initialize : function(){
            oTable=$('#invoices-data-table').dataTable( {
                "bServerSide": true,
                "bProcessing": true,
                "bFilter": true,
                "bDestroy": true,
                "iDisplayLength": 25,
                "sPaginationType": "full_numbers",
                "sAjaxSource": site_url+'/admin/vendors/ajax-get-vendors-invoices/?'+$('#invoice_filter').serialize(),
                "aoColumnDefs":[
                                { "bSortable": true, "aTargets": [ 0 ] },
                                { "bSortable": false, "aTargets": [ 1 ] },
                                { "bSortable": true, "aTargets": [ 2 ] },
                                { "bSortable": true, "aTargets": [ 3 ], "sType": "date" },
                                { "bSortable": true, "aTargets": [ 4 ], "sClass": "money" }, 
                                { "bSortable": true, "aTargets": [ 5 ], "sClass": "money" }, 
                                { "bSortable": false, "aTargets": [ 6 ] }
                                ],   // Turning sorting on/off for cols
                "sServerMethod": "POST",
                "oLanguage": {
                    "sSearch": "Search Vendors:"
                },
                "aaSorting": [[1,'desc']], // Initial sorting order when page loads
                "fnInitComplete": function (oSettings, json) {
                    $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
                }
            } );
            $('#invoices-data-table').css('width', '100%');
        }
    }

    vendor_lineitems={
        show_invoice_lineitems : function(){
//            console.log(e);
            console.log("Hello world");
        }
    }

    function init_payment_link(){
        $(document).on('click', 'a.payment_link', function(){
            window.location.href = site_url+'/admin/vendors/show-invoice/inv_id/'+$(this).attr('id'); //+'/invoice_number/'+$(this).attr('rel');
        });
    }

    function init_lineitems_link(){
        $(document).on('click','a.lineitems_link',function(){
            $id=$(this).attr('id');
//            console.log($id);
            $.fancybox({
                'width'                 : 900,
                'height'                : 500,
                'href'                  :  site_url+"/admin/vendors/show-invoice-line-items/id/"+$id,
                'transitionIn'         : 'none',
                'transitionOut'        : 'none',
                'padding'               : 20,
                'speedIn'               : 0,
                'type'                  : 'iframe',
                'changeSpeed'           : 0,
                'changeFade'            : 0,
                'speedOut'              : 0,
                'overlayColor'          : '#FFF',
                'title'                 : '<h3>Invoices Line Items</h3>',
                'titlePosition'        : 'inside'
            });
            return false;
        });
    }
</script>
