<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('vendors/vendor-sidebar-menus.phtml', array('selected' => 'invoices', 'id' => $this->vendor->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<div class="one">
    <div class="one_third">
        <h2><?php echo $this->vendor->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Vendor Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->vendor->user_status)); ?></h4>       
        </div>
    </div>    
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>
<a href="<?php echo $this->baseUrl('admin/vendors/invoice-create-vendor/id/'.$this->vendor->id); ?>" class="iconlink2"><img src="<?php echo $this->baseUrl(); ?>/assets/images/icons/small/black/plus.png" class="mgright5" alt=""> <span>Create An Invoice</span></a> &nbsp;
<div class="spacer"></div>
<table cellpadding="0" cellspacing="0" border="0" class="dyntable sTable2" id="invoices-data-table">
    <thead>
        <tr>
            <th class="head0"  width="160">Inv #</th> <!--invoice.invoice_number-->
            <th class="head1">Inv Year - Qtr</th> <!--invoice.fiscal_year - invoice.quarter-->
            <th class="head1">Inv Date</th> <!--invoice.invoice_date-->
            <th class="head1">Inv Type</th> <!--invoice.invoice_type-->           
            <th class="head1">Inv Status</th> <!--if quarter 3 payment-->
            <th class="head1">Pmt Status</th> <!--invoice.payment_status-->
            <th class="head1">Invoice Total</th> <!--invoice.amount_due-->
            <th class="head0" >Amt Paid</th> <!--sum(invoice_lineitems.amount_paid)-->
            <th class="head0" width="80">Action</th>
        </tr>            
    </thead>
</table>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px; 
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
    .ui-tooltip-content{
        font-size:110%;
        line-height: 150%
    }
    .ui-tooltip, .qtip{
        max-width: 500px; 
    }
    .align-right{
        text-align: right!important;
    }

    .align-center{
        text-align: center!important;
    }
    tr.odd td{
        background-color: #ECECEF;
    }
    #invoices-data-table tbody td{
        border-right:1px solid #FFF;
    }
</style>   

<script type="text/javascript">
    /** Datatable code **/
   
    
    var oTable;
    $(window).bind('load',function(){
        oTable=$('#invoices-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "iDisplayLength": 25,            
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/vendors/ajax-get-invoices/id/<?php echo $this->vendor->id; ?>',
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Invoices by Invoice: "                
            },
            "aoColumns" : [   
                { sWidth:'10%' ,sClass: "align-center" },                  
                { sClass: "align-center" }, 
                { sClass: "align-center" }, 
                { sWidth:'10%', sClass: "align-center" },
                { sClass: "align-right" }, 
                { sClass: "align-right" }, 
                { sClass: "align-right" }, 
                { sClass: "align-right" }, 
                { sWidth:'10%', sClass: "align-center" } 
            ],
            "aaSorting": [[2,'desc']], // Initial sorting order when page loads
            "aoColumnDefs":[
                { "bSortable": true, "aTargets": [ 0 ] },
                { "bSortable": true, "aTargets": [ 1 ] },
                { "bSortable": true, "aTargets": [ 2 ] },
                { "bSortable": false, "aTargets": [ 3 ]},
                { "bSortable": false, "aTargets": [ 4 ] },
                { "bSortable": false, "aTargets": [ 5 ] },
                { "bSortable": false, "aTargets": [ 6 ] },
                { "bSortable": false, "aTargets": [ 7 ] },
                { "bSortable": false, "aTargets": [ 8 ] }],  // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {
                $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
            },
            fnDrawCallback:function(){
                init_vendor_link();
            }            
        } ); 
        $('#invoices-data-table').css('width', '100%');
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_vendor_link();
        init_invoice_link();
    });    
    
    function init_vendor_link(){
        $(document).on('click','a.invoices_link',function(){
            $id=$(this).attr('rel');            
            $.fancybox({
                'width'                 : 900,
                'height'                : 500,
                'href'                  :  site_url+"/admin/vendors/show-invoice-line-items/id/"+$id,    
                'transitionIn'         : 'none',
                'transitionOut'        : 'none',
                'padding'               : 20,
                'speedIn'               : 0,
                'type'                  : 'iframe',
                'changeSpeed'           : 0,            
                'changeFade'            : 0,
                'speedOut'              : 0,
                'overlayColor'          : '#FFF',
                'title'                 : '<h3>Invoices Line Items</h3>',
                'titlePosition'        : 'inside'
            });        
            return false;
        });                         
    }
    
    function init_invoice_link(){
        $(document).on('click', 'a.invoice_link', function(){            
            window.location.href = site_url+"/admin/vendors/show-invoice/inv_id/"+ $(this).attr('rel');            
        });
    }
    
    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                return;
            }
        });
    }
    
    function init_alphabetical_filters(){
        $('.letter_filter').on('click',function(){
            oTable.fnFilter($(this).text());
        });
    }
    
    /** Datatable code **/
    $(function(){
        $(document).on('click', 'a.delete_invoices', function(){
            if(confirm('Are you sure to delete this Invoice ? \n Please note that all the line items associated with this one will also be deleted.')){
                $note_id=$(this).attr('rel').split("-")[1];
                $.ajax({
                    url:site_url+'/admin/vendors/ajax-delete-invoices/inv_id/' + $(this).attr('rel'),
                    dataType:'json',
                    data : '',
                    type:'post',
                    success:function(e){
                        $.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                        if(e.code=='success'){
                            oTable.fnDraw();
                        }
                    }
                });
            }
            return false;
        });
    })
        
</script>
