<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('vendors/vendor-sidebar-menus.phtml',array('selected'=>'payments','id'=>$this->vendor->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<?php echo $this->muhaha; ?>
<div class="one">
    <div class="one_third">
        <h2><?php echo $this->vendor->organization_name; ?></h2>
    </div>
    <div class="container_left">
        <h3>Vendors&nbsp;Status:</h3>
    </div>
    <div class="container_right">
        <h4><?php echo ucfirst(strtolower($this->vendor->user_status)); ?></h4>       
    </div>
</div>
<div class="spacer"></div>
<hr size="1" /><br />
