<div id="view-content">
    <h1>Review Registrant</h1>
    <div class="spacer clear"></div>
    <hr size="1" noshade />
    <div class="spacer clear"></div>
    
    <div style="display: none;">
        <div id="loader"><img src="<?php echo $this->baseUrl("assets/images/loading.gif"); ?>" /></div>
    </div>  
   
    <div class="form_container_left">
        <?php echo $this->form->username->setAttrib('readonly', 'true'); ?>                                
    </div>
    <div class="form_container_right">
            <?php echo $this->form->email->setAttrib('readonly', 'true');; ?>                            
    </div>
    <div class="spacer clear"></div>
    <hr size="1" noshade />
    <div class="spacer"></div>
    
    <div class="form_container_left">
        <?php echo $this->form->organization_name->setAttrib('readonly', 'true'); ?>
        <div class="spacer"></div>
        <?php echo $this->form->address_line_1->setAttrib('readonly', 'true'); ?>
        <div class="spacer"></div>
        <?php echo $this->form->address_line_2->setAttrib('readonly', 'true'); ?>
        <div class="spacer"></div>
        <div class="one_third">
            <?php echo $this->form->city->setAttrib('readonly', 'true'); ?>
        </div>
        <div class="one_third">
            <?php echo $this->form->state->setAttrib('readonly', 'true'); ?>
        </div>
        <div class="one_fifth">
            <?php echo $this->form->zip->setAttrib('readonly', 'true'); ?>
        </div><div class="clear"></div>
        <?php echo $this->form->company_email->setAttrib('readonly', 'true'); ?>
        <div class="spacer clear"></div>
    </div>

    <div class="form_container_right">
        <?php echo $this->form->phone_1->setAttrib('readonly', 'true'); ?>
        <div class="spacer"></div>
        <?php echo $this->form->phone_2->setAttrib('readonly', 'true'); ?>
        <div class="spacer"></div>
        <?php echo $this->form->fax->setAttrib('readonly', 'true'); ?>
        <div class="spacer"></div>
        <?php echo $this->form->web_page->setAttrib('readonly', 'true'); ?>
        <div class="spacer clear"></div>
    </div>    
    <div class="clear"></div>
   
    <div class="spacer"></div>
    <?php //if($this->link == 'review_link'): ?>
    <form action="" name="vendor_approve_form" id="vendor_approve_form">
        <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id; ?>" />
        <button type="button" name="decline" id="decline" value="" class="button button_blue detail_button">Decline</button>
        <button type="button" name="approve" id="approve" value="" class="button button_blue detail_button">Approve</button>
    </form>
    <?php //endif; ?>
</div>

<style type="text/css">
#city,#state,#zip,#sal{
    width:110px;
}
#first_name{
    width:250px;
}
.selected_products{
    width: 390px !important;
}
.profile_logo img{
    border: 1px solid #cccccc;
}
.profile_logo{
    float: left;
    width: 110px;    
}
.sample_products{
    /*float: right;*/
    /*border: 1px solid;*/
}
.sampleimg{
    border: 1px solid #cccccc;
    margin: 10px 10px 0 0;
    float: left;
    padding: 1px;
    width: 80px;
}
#ctnDectineIamges{
    display: none;
}
</style>

<script type="text/javascript">
    $(document).on('click', '#decline', function(){
        window.parent.execute_parent($('#user_id').val(), this.id);        
    });            
    
    $(document).on('click', '#approve', function(){
        window.parent.execute_approval($('#user_id').val(), this.id);        
    });
    
</script>
