<?php if (sizeof($this->items)): ?>
    <?php
    $quarters = array(0 => 'N/A', 1 => 'First', 2 => 'Second', 3 => 'Third', 4 => 'Fourth');
    $alt = true;
    $currency = new Zend_Currency('en_US');
    ?>
    <h4>Invoice ID : <?php echo $this->Invoice_number; ?></h4>
    <table cellpadding="0" cellspacing="0" border="1" class="sTable2" width="100%">
        <thead>
            <tr role="row">
                <th>Line Items #</th>
                <th>Client</th>
                <th>Status</th>
                <th>Fiscal Year</th>
                <th>Quarter</th>
                <th>Date</th>
                <th>Check Number</th>
                <th>Invoice Total</th>
                <th>Amount Paid</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = $total_due = $total_paid = 0; ?>
            <?php foreach ($this->items as $item): ?>
            <?php $i++; $total_due += $item->amount_due; $total_paid += $item->amount_paid; ?>
            <?php
				$orgnizationName = ($item->client_id instanceof \BL\Entity\User) ? $item->client_id->organization_name : 'N/A';
               	$client_id = $item->client_id;
               	$status = isset($this->status_array[$item->license_status])? $this->status_array[$item->license_status]: "Unlicensed";
                error_log("\nstatus: " . $item->license_status,3, "./errorLog.log");
	   		?>
                <tr class="<?php echo ($alt = !$alt) ? "odd" : "even"; ?>">
                    <td><?php echo $i; ?></td>
                    <td><?php echo $orgnizationName?></td>
                    <td><?php echo $status?></td>
                    <td><?php echo $item->fiscal_year; ?></td>
                    <td><?php echo !is_null($item->quarter) ? $quarters[$item->quarter] : 'N/A'; ?></td>
                    <td><?php echo ( (int) $item->created_at->format("Y") > 0 ? $item->created_at->format("m/d/Y") : 'N/A'); ?></td>
                    <td><?php echo $item->check_number; ?></td>
                    <td><?php echo $currency->toCurrency($item->amount_due); ?></td>
                    <td><?php echo $currency->toCurrency($item->amount_paid); ?></td>
                </tr>
            <?php endforeach; ?>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td class="total_txt">Total</td>
                    <td class="total_amt"><?php echo $currency->toCurrency($total_due); ?></td>
                    <td class="total_amt"><?php echo $currency->toCurrency($total_paid); ?></td>
                </tr>
        </tbody>
    </table>
<?php else: ?>
    <h2>No line items found</h2>
<?php endif; ?>

    <style type="text/css">
        .total_txt{font-weight: bold; text-align: right;}
        .total_amt{font-weight: bold;}
    </style>