<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('vendors/vendor-sidebar-menus.phtml', array('selected' => 'payments', 'id' => $this->vendor->id));
$this->placeholder('main_side_bar')->captureEnd();
?>
<div class="one">
    <div class="one_third">
        <h2><?php echo $this->vendor->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Vendor Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->vendor->user_status)); ?></h4>       
        </div>
    </div>      
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<table cellpadding="0" cellspacing="0" border="0" class="dyntable" id="payments-data-table">
    <thead>
        <tr>
            <th class="head1" width="160">Id</th>
            <th class="head0">Type</th>
            <th class="head1" width=>Ref #</th>
            <th class="head0" width=>Invoice</th>
            <th class="head1" width="15%">Date</th>
            <th class="head0">Pmt Amt</th>
            <th class="head1">Amt to Client</th>
            <th class="head0">Amt to AMC</th>
            <th class="head1">Amt Due</th>
            <th class="head0">Remaining</th>
            <th class="head1" width="80">Action</th>
        </tr>            
    </thead>
</table>

<script type="text/javascript">
    /** Datatable code **/
    var oTable;
    $(window).bind('load',function(){
        oTable=$('#payments-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "iDisplayLength": 20,            
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/vendors/ajax-get-vendor-payments/id/<?php echo $this->vendor->id; ?>',
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Payments by CK #:"                
            },
             "aoColumns" : [   
                { sWidth:'10%'},   
                { sWidth:'10%', sClass: "align-center" },
                { sClass: "align-center" }, 
                { sClass: "align-center" }, 
                { sClass: "align-center" }, 
                { sClass: "align-right" },
                { sClass: "align-right" },
                { sClass: "align-right" },
                { sClass: "align-right" }, 
                { sClass: "align-right" }, 
                { sWidth:'10%', sClass: "align-center" } 
            ],
            "aaSorting": [[0,'desc']], // Initial sorting order when page loads
            "aoColumnDefs":[{ "bSortable": false, "aTargets": [ 1,2,3,4,5,6,7,8,9,10 ] }],  // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {
                $('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
            },
            fnDrawCallback:function(){
                init_vendor_link();
            }            
        } ); 
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_vendor_link();
    });    
    
    function init_vendor_link(){
        $(document).on('click','a.vendor_payment_link',function(){
            $id=$(this).attr('rel');
            $.fancybox({
                'width'                 : 900,
                'height'                : 500,
                'href'                  :  site_url+"/admin/vendors/show-vendor-payment-line-items/id/"+$id,    
                'transitionIn'         : 'none',
                'transitionOut'        : 'none',
                'padding'               : 20,
                'speedIn'               : 0,
                'type'                  : 'iframe',
                'changeSpeed'           : 0,            
                'changeFade'            : 0,
                'speedOut'              : 0,
                'overlayColor'          : '#FFF',
                'title'                 : '<h3>Payment Line Items</h3>',
                'titlePosition'        : 'inside'
            });        
            return false;
        })       
    }
    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                return;
            }
        });
    }
    
    function init_alphabetical_filters(){
        $('.letter_filter').on('click',function(){
            oTable.fnFilter($(this).text());
        });
    }
    /** Datatable code **/
    
    $(function(){
        $(document).on('click', 'a.delete_payment', function(){
            if(confirm('Are you sure to delete this payment ? \n Please note that all the line items associated with this one will also be deleted.')){
                $note_id=$(this).attr('rel').split("-")[1];
                $.ajax({
                    url:site_url+'/admin/vendors/ajax-delete-payment/',
                    dataType:'json',
                    data : '',
                    type:'post',
                    success:function(e){
                        $.jGrowl(e.msg,{header:"<b>"+e.code+"</b>"});
                        if(e.code=='success'){
                            oTable.fnDraw();
                        }
                    }
                });
            }
            return false;
        });
    })
</script>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px; 
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }
    .ui-tooltip-content{
        font-size:110%;
        line-height: 150%
    }
    .ui-tooltip, .qtip{
        max-width: 500px; 
    }
    .align-right{
        text-align: right!important;
    }

    .align-center{
        text-align: center!important;
    }
    tr.odd td{
        background-color: #ECECEF;
    }
    #payments-data-table tbody td{
        border-right:1px solid #FFF;
    }
</style>   
