<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('vendors/vendor-sidebar-menus.phtml', array('selected' => 'web-profile', 'id' => $this->vendor->id));
$this->placeholder('main_side_bar')->captureEnd();
?>

<div class="one">
    <div class="one_third">
        <h2><?php echo $this->vendor->organization_name; ?></h2>
    </div>
    <div class="rightalign">
        <div class="leftalign">
            <h3>Vendor Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <h4><?php echo ucfirst(strtolower($this->vendor->user_status)); ?></h4>
        </div>
    </div>
</div>
<br />
<hr size="1" noshade />
<div class="spacer"></div>

<form  method="POST" enctype="multipart/form-data" id="<?php echo $this->form->getName(); ?>">
    <?php
        $errorsMessages = $this->form->getMessages();
    ?>
    <div class="form_container_left">
        <?php echo $this->form->organization_name; ?>
        <?php echo $this->form->address1; ?>
        <?php echo $this->form->address2; ?>
        <div class="one_third">
            <?php echo $this->form->city; ?>
        </div>
        <div class="one_third">
            <?php echo $this->form->state; ?>
        </div>
        <div class="one_fifth">
            <?php echo $this->form->zip; ?>
        </div><div class="clear"></div>
        <?php echo $this->form->email; ?>
        <div class="clear"></div>
    </div>

    <div class="form_container_right extSpace">
        <?php echo $this->form->phone1; ?>
        <?php echo $this->form->phone2; ?>
        <?php echo $this->form->fax; ?>
        <?php echo $this->form->web_page; ?>
    </div>
    <div class="clear"></div>

    <div class="form_container_left">
        <?php echo $this->form->logo_url; echo $this->form->use_default."<br/>";?>
        The optimal size of the logo should be 250px X 250px.
        <?php
        //echo $this->baseUrl();
        if($this->logo!=''){
        ?>
        &nbsp;&nbsp;<a class="example1" href="<?php echo $this->baseUrl("assets/files/vendor_profile/".$this->logo); ?>">View logo</a>
        <?php
        }
        ?>

    </div>
    <div class="clear"></div>
    <div class="spacer"></div>
    <?php echo $this->form->services; ?>
    <div class="clear"></div>
    <hr size="1" noshade />
    <div class="spacer"></div>
    <?php //echo $this->form->product_offered;?>

    <?php echo $this->form->product_category; ?>
    <?php echo $this->form->product; ?>
    <button type="button" id="select_button" class="button button_black">Add</button>
    <div class="spacer"></div>
    <p id="otherProductDiv" style="display: none">
        <label>Enter Other Product :</label>
        <input type="text" size="20" id="other_product" class="other_product_txt txtinput" value="" />
        <img src="<?php echo $this->baseUrl("assets") ?>/images/loaders/loader3.gif" class="leftmargin" id="product_add_loader" />
        <img src="<?php echo $this->baseUrl("assets") ?>/images/delete_cross.gif" class="leftmargin hand_cursor" id="hide_other_product" />
    </p>
    <div class="spacer"></div>
    <?php
    if (isset($errorsMessages['products']['isEmpty']))
        echo '<span style="color:red;">' . $errorsMessages['products']['isEmpty'] . '</span>';
    ?>
    <span id="product_val_set" class="one txtinput selected_products">
        <?php
        $total_products = '';
        if(sizeof($this->products)){
            foreach($this->products as $product){
            $total_products .= $product['id'].',';
            ?>
            <a href="#<?php echo $product['id'];?>" class="cross" style="text-decoration:none;" rel="<?php echo $product['id'];?>"><?php echo $product['product_name'];?><img align="absmiddle" src="<?php echo $this->baseUrl('assets') ?>/images/delete.png"/> </a>
        <?php
            }
            $total_products = substr($total_products,0,-1);
        }
        ?>
    </span>
    <?php echo $this->form->products; ?>
    <div class="spacer"></div>
    <?php echo $this->form->company_description;?>

    <div class="spacer"></div>
</form>
<hr size="1" noshade />
<div class="spacer"></div>

<div style="position: relative;">
    <div style="width:60%;float:left;">
        <table cellpadding="0" cellspacing="0" border="0" class="dyntable" id="banners-data-table">
            <thead>
                <tr>
                    <th class="head1" width="25%">Added on</th>
                    <th class="head0" width="45%">Title</th>
                    <th class="head1" width="25%">File</th>
                    <th class="head0" width="30%">Action</th>
                </tr>
            </thead>
        </table>
    </div>
    <div style="float: left;margin-left: 40px;">
        <?php if(sizeof($this->vendorSampleFile)<10): ?>
        <button type="button" id="upload_sample" class="button button_black detail_button">Add Product Sample</button>&nbsp;&nbsp;
        <?php endif; ?>
    </div>
    <div class="clear"></div>
    <div class="spacer"></div>
    <button type="button" id="btnSubmit" class="button button_black detail_button">Submit</button>
</div>

<style type="text/css">
#city,#state,#zip,#sal{
    width:110px;
}
#first_name{
    width:250px;
}
#events-data-table {
    border-collapse: collapse;
}
#events-data-table tr td {
    border-bottom: 1px solid #DDDDDD;
    border-right: 1px solid #FFFFFF;
    padding: 8px 10px;
    vertical-align: top;
}
#events-data-table thead th {
    border-right: 1px solid #777777;
    color: #CCCCCC;
    font-size: 12px;
    padding: 8px 10px;
    text-shadow: 1px 1px #444444;
    text-transform: uppercase;
}
#events-data-table thead th {
    font-weight: normal;
    text-align: left;
}
#events-data-table tr td:last-child {
    border-right: 0 none;
}
#events-data-table tr:last-child td {
    border-bottom: 0 none;
}
#events-data-table tr:hover {
    background: none repeat scroll 0 0 #CACACA;
}
#events-data-table tr.selected {
    background: none repeat scroll 0 0 #FFFCCC;
}
#events-data-table .head0 {
    background-color: #A79269;
}
#events-data-table .head1 {
    background-color: #77623D;
}
#events-data-table .odd {
    background-color: #EAEAEA;
}
#events-data-table .even {
    background-color: #DDDDDD;
}

.dataTables_processing {
    position: absolute;
    top: 15px;
    left: 50%;
    width: 100px;
    margin-left: -125px;
    background-color: #E30;
    text-align: center;
    color: #FFF;
    padding: 2px 0;
    -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
}
#banners-data-table td{
    vertical-align: middle;
}

#city,#state,#zip,#sal{
    width:110px;
}
.jGrowl-notification{
background-color: #917C54 !important;
}
.aa{
    width: 60% !important;
    text-align: left !important;
}
</style>

<script type="text/javascript">
    /** Datatable code **/
    var oTable;
    $(window).bind('load',function(){
        oTable=$('#banners-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "iDisplayLength": 5,
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/admin/vendors/ajax-get-sample-product/redirect_url/web-profile/use_for/web_profile/id/'+<?php echo $this->vendor_id;?>,
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search by Title:"
            },
            "aaSorting": [[1,'desc']], // Initial sorting order when page loads
            "aoColumnDefs":[{ "bSortable": false, "aTargets": [ 2,3 ] }],  // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {

            }
        } );

        $('.default').parent().addClass('aa');
        $('#banners-data-table_length label').html('<h2>Upload Promotional Product Images</h2>');
        init_action_links();
        init_server_search_fix();   // Will search only hitting enter not keypress
    });

    function init_action_links(){

        $(document).on('click','a.fancy',function(){
            $src=$(this).find("img").attr("src").replace("thumbs/","");
            $.fancybox({
                'href'                  : $src,
                'transitionIn'         : 'none',
                'transitionOut'        : 'none',
                'autoScale'        : true,
                'autoDimensions'    :   true,
                'padding'               : 20,
                'speedIn'               : 0,
                'type'                  : 'image',
                'changeSpeed'           : 0,
                'changeFade'            : 0,
                'speedOut'              : 0,
                'overlayColor'          : '#FFF',
                'titlePosition'        : 'inside'
            });
            return false;
        });

        $(document).on('click','a.delete',function(){
            if(confirm("Are you sure to delete this banner ?")){
                return true;
            }
            return false;
        })
    }

    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                return;
            }
        });
    }
    /** Datatable code **/
</script>

<script type="text/javascript">

$(document).ready(function() {

    $("a.example1").fancybox();

    $(document).on('click', '#upload_sample', function(){
        
        if($("#uploaded_pics").find("img").size()<5){

        upload_left=$("#uploaded_pics").find("img").size() ? (5-$("#uploaded_pics").find("img").size()) : 5;
            $.fancybox({
                'width'                 : 650,
                'height'                : 350,
                'title'                 : '<h4>Upload Product Sample. (Max '+upload_left+')</h4>',
                'titlePosition'         : 'inside',
                'autoDimensions'        : false,
                'href'                  : site_url+"/admin/vendors/upload-files/max/"+upload_left,
                'transitionIn'          : 'elastic',
                'transitionOut'         : 'none',
                'type'                  : 'iframe'
            });
        }else{
            alert("You have reached the maximum number of files to be uploaded")
        }
        return false;
    })

    $('#btnSubmit').click(function(){
        $('#vendor_profile').find('.title').remove();
        $('#banners-data-table .title').clone(true).attr('type','hidden').appendTo("#vendor_profile");
        $('#vendor_profile').submit();
    });

    $('.cross').live('click',function(){
        var ans = confirm("Are you sure to delete?");
        if(ans){
            $(this).remove();
            update_hidden_products();
        }
    });

    //Change product list using selected product category
    $("#product_category").change(function(){

        if($("#product_category option:selected").text() == 'Other'){
            $("#product").attr('disabled', 'disabled');
            $("#otherProductDiv").show();
            $("#product_add_loader").hide();
        }
        else{
            $("#product").removeAttr('disabled');
            $("#otherProductDiv").hide();

            $.ajax({
                dataType: 'html',
                url: '<?php echo $this->url(array('controller' => 'vendors', 'action' => 'product')); ?>?cat='+$("#product_category").val(),
                success: function( response ) {
                    $("#product").html(response);
                }
            });
        }
    });

    $("#hide_other_product").click(function(){
        console.log("Hide other product");
        $("#product_category").val('');
        $("#product").removeAttr("disabled");
        $("#otherProductDiv").hide();
    });


    $("#products").val('<?php  echo $total_products;?>');

    $("#select_button").click(function(){
        var product = $("#product");
        $("#product_error").html("&nbsp;");
        if($("#product option:selected").text() != 'Select product' && (!$('#product').is(':disabled'))){
            var p_id = $("#product option:selected").val();
            var p_name = $("#product option:selected").text();
            if(check_existence(p_id)==p_id){
                $.jGrowl('You alreday Added '+p_name+'. Try a new one.');
            }
            else{
                add_products_display(p_id,p_name);
            }
        }
        else if(($("#product option:selected").text() == 'Select product') && (!$('#product').is(':disabled'))){
            //alert('3');
            $.jGrowl("Please add product from product list.");
        }
        else{
            if($("#other_product").val() != ''){
                var relId="";
                var otherid = ($('#product_category').val());
                $.ajax({
                    type: 'POST',
                    beforeSend: function() { $('#product_add_loader').show(); },
                    complete: function() { $('#product_add_loader').hide(); },
                    url:  '<?php echo $this->url(array('controller' => 'license', 'action' => 'other-check')); ?>?otherid='+otherid+'&productName='+$('#other_product').val(),
                    cache: false,
                    success: function(html)
                        {
                        var p_id = html;
                        add_products_display(p_id,$('#other_product').val());
                        }
                });
            }
            else{
                $.jGrowl("Please enter product name.");
            }
        }
    });

}); // end document ready


function update_hidden_products(){
    var product_val ='';
    var ctn = '';
    $('.cross').each(function(el){
        var pid = $(this).attr('rel');
        var pname = $(this).text();
        product_val+=pid+',';
        ctn += '<a rel="'+pid+'" style="text-decoration:none;" class="cross" href="#'+pid+'">'+pname+'<img align="absmiddle" src="'+site_url+'/assets/images/delete.png"></a>';
    });
    product_val = product_val.substring(0, product_val.length - 1);
    $('#products').val(product_val);
    $('#product_val_set').html(ctn);
}

function add_products_display(pid,pname){
    var ctn = '<a rel="'+pid+'" style="text-decoration:none;" class="cross" href="#'+pid+'">'+pname+'<img align="absmiddle" src="'+site_url+'/assets/images/delete.png"></a>';
    $('#product_val_set').append(ctn);
    update_hidden_products();
}

function check_existence(pid){
    return $('.cross[rel="'+pid+'"]').attr('rel');
}

function add_picture_to_form(pic){

    if($("#uploaded_pics").find("img").size()<5){

        var row_class='';
        if($('#events-data-table > tbody > tr').length%2==0){
            row_class='even';
        }else{
            row_class='odd';
        }

        var now = new Date();
        var update_date = '<?php echo date("m/d/yy") ;?>';

        $("#vendor_profile").append('<input type="hidden" name="pics[]" value="'+pic+'" />');
        var image_path = site_url+'/assets/files/samples/products/thumbs/'+pic;
        //var large_image = site_url+'/assets/files/samples/products/'+pic;
        $("#banners-data-table tbody").append('<tr class="'+row_class+'"><td>'+update_date+'</td>'
            +'<td><input type="text" name="title[]" class="title" value=""/></td>'
            +'<td><img height="50" src="'+image_path+'"/></td>'
            +'<td>&nbsp;</td>'
            );
    }else{
        alert("Maximum 5 pictures can be added");
    }
}
</script>
