<!--<h2>Search By Lisc. Agreements</h2>-->
<div class="one">
    <div class="one_third"><h2 class="grid_cap">Search By Lisc. Agreements</h2></div>
    <div class="rightalign" id="status_filter">
        <div class="leftalign">
            <h3>Vendors Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <select name="vendor_status" id="vendor_status" multiple="multiple" >
                <?php
                foreach ($this->user_status as $key => $status) {
                    echo '<option value="' . $status . '"> ' . $status . '</option>';
                }
                ?>
            </select>
        </div>
    </div>
</div>
<div class="clear"></div>
<hr size="1"/>

<form action="" method="POST" enctype="multipart/form-data" id="search-lisc-agreements-form">
    <input type="hidden" name="search_type" value="lisc-agreements" />
    <div class="spacer"></div>
    <label>Vendor Name<br />
        <input type="text" class="text" id="vendor_name" name="vendor_name" />
    </label>
    <div class="spacer"></div>
    <label>License #<br />
        <input type="text" class="text" id="license_num" name="license_num" />
    </label>
    <div class="spacer"></div>
    <label>Client by Org Name<br />
        <input type="text" class="text" id="client_org_name" name="client_org_name" />
    </label>
    <div class="spacer"></div>    
    <div class="one_third">
        <label>Status by Client<br />
            <select name="client_status">
                <option value="">Select</option>
                <option value="1">Current</option>
                <option value="4">One-time</option>
                <option value="2">Canceled</option>
            </select>
        </label>
    </div>
    <div class="one_fourth" >
        <label>Sharing<br />
            <select name="sharing">
                <option value="">Select</option>
                <option value="yes">Yes</option>
                <option value="">No</option>
            </select>
        </label>
    </div>
    <div class="one_fifth">
        <label>Renewal Fee<br />
            <input name="renewal_free" type="text" id="renewal_free" class="text" />
        </label>
    </div>

    <div class="clear"></div>
    <div class="spacer"></div>
    <label>Vendor Type<br />
        <select name="vendor_type">
            <option value="">Select</option>
            <option value="1">1: Vendors that pay a royalty fee based on a percentage commission</option>
            <option value="2">2: Vendors that pay a royalty fee based on unit sales</option>
            <option value="3">3: Vendors that have a unique royalty structure.</option>
        </select>
    </label>
    <div class="spacer"></div>
    <label>
        Percentage of quarterly sales to be paid as royalty:<br />
        <input type="text" class="text" name="quarterly_sales_royalty" id="quarterly_sales_royalty" />
    </label>
    <div class="spacer"></div>
    <label>
        Advance royalty:<br />
        <input type="text" class="text" name="advance_royalty" id="advance_royalty" />
    </label>
    <div class="spacer"></div>
    <label>
        Royalty description:<br />
        <input type="text" class="text" name="royalty_description" id="royalty_description" />
    </label>
    <div class="spacer"></div>
    <label>
        Grant of License:<br />
        <input type="text" class="text" name="grant_of_lisc" id="grant_of_lisc" />
    </label>
    <div class="spacer"></div>
    <div class="spacer"></div>
    <button type="submit" class="button button_black detail_button">Search</button>
</form>
<script type="text/javascript">
    var status = 'all';
    $(function(){
        $("#search-lisc-agreements-form").on('submit',function(){
            status = $("#vendor_status").val();
            if(status == 'null' || status == null){
                status = 'all';
            }
            window.parent.executeSearch($(this).serialize()+'&vendor_status='+status,'Search Vendors by Lisc. Agreements','lisc-agreements');
            return false; 
        });
    })
    $("#vendor_status").multiselect({
        selectedText: "# of # selected"
    });
</script>
<style type="text/css">
    #renewal_free{
        width:110px;
    }
    #last_select{
        padding-left: 20px;
    }
</style>
