<?php
//$this->headScript()->appendFile($this->baseUrl("assets/js/plugins/jquery-ui-1.8.16.custom.min.js"));
//$this->headLink()->appendStylesheet($this->baseUrl("assets/css/ui_themes/Aristo/Aristo.css"));
?>
<!--<h2>Search By Payments</h2>-->
<div class="one">
    <div class="one_third"><h2 class="grid_cap">Search By Payments</h2></div>
    <div class="rightalign" id="status_filter">
        <div class="leftalign">
            <h3>Vendors Status:&nbsp;&nbsp;</h3>
        </div>
        <div class="leftalign">
            <select name="vendor_status" id="vendor_status" multiple="multiple" >
                <?php
                foreach ($this->user_status as $key => $status) {
                    echo '<option value="' . $status . '"> ' . $status . '</option>';
                }
                ?>
            </select>
        </div>
    </div>
</div>
<div class="clear"></div>
<hr size="1"/>
<form action="" method="POST" enctype="multipart/form-data" id="search-payments-form">
    <input type="hidden" name="search_type" value="payments" />
    <div class="spacer"></div>
    <div class="form_container_left">
        <?php echo $this->form->vendor_name; ?> 
        <div class="one_half">
            <?php echo $this->form->date_from; ?> 
        </div>
        <div class="one_third">
            <?php echo $this->form->date_to; ?> 
        </div>
        <div class="clear"></div>
        <?php echo $this->form->reference; ?> 
        <?php echo $this->form->payment_year; ?> 
    </div>
    <div class="form_container_right">
        <?php echo $this->form->payment_id; ?> 
        <?php echo $this->form->invoice_number; ?> 
        <?php echo $this->form->payment_amount; ?> 

        <!--        <div class="one_third">
                    <label>Payment Type<br />
                        <select name="payment type">
                            <option value="">Select</option>
                            <option value="check">Check</option>
                            <option value="ach">ACH</option>                
                        </select>
                    </label>
                </div>-->
        <div class="one_third">
            <label>Payment Qtr<br />
                <select name="payment_qtr">
                    <option value="">Select</option>
                    <option value="1">First</option>
                    <option value="2">Second</option> 
                    <option value="3">Third</option>
                    <option value="4">Fourth</option>                 
                </select>
            </label>
        </div>

        <div class="one_half">
            <div class="spacer"></div><div class="spacer"></div>
            <button type="submit" class="button button_black detail_button">Search</button>
        </div>
    </div>

    <!--    <div class="clear"></div>
        <div class="spacer"></div>
        <button type="submit" class="button button_black detail_button">Search</button>-->
</form>
<script type="text/javascript">
    var status = 'all';
    $(function(){
        $("#vendor_name")[0].focus();
        $(".date").datepicker({
            dateFormat:"mm/dd/yy"
        });
        $("#search-payments-form").on('submit',function(){
            status = $("#vendor_status").val();
            if(status == 'null' || status == null){
                status = 'all';
            }            
            window.parent.executeSearch($(this).serialize()+'&vendor_status='+status,'Search Vendors By Payments','payments');
            return false; 
        });
    })
    $("#vendor_status").multiselect({
        selectedText: "# of # selected"
    });    
</script>
<style type="text/css">
    #payment type{
        width:200px;
    }
</style>