<?php
$this->placeholder('main_side_bar')->captureStart();
echo $this->partial('layout/sidebar-calendar.phtml');
$this->placeholder('main_side_bar')->captureEnd();
?>
<div id="view-content">	
    <h2>Events</h2>
<div class="notification msginfo">
    <a class="close"></a>
Events listed here are viewable on your licensed vendors' calendars. If you would like to add an event please email the details (event title, date range, start/end time, location and description) and your desired audience (all licensed vendors, select licensed vendors, etc.) to <a href="mailto:admin@greeklicensing.com">admin@greeklicensing.com </a>
</div>
    <div class="spacer"></div>
    <div style="float: left">
        <ul class="submenu" id="page_select" style="border:0 none; padding: 0px;">
            <li id="all"><a rel="all" href="javascript:;">All</a></li>
            <li class="current" id="upcoming"><a rel ="upcoming" href="javascript:;">Upcoming</a></li>
            <li id="past"><a rel="past" href="javascript:;">Past</a></li>
        </ul>
    </div>
    <div class="spacer"></div>
    <table cellpadding="0" cellspacing="0" border="0" class="dyntable" id="events-data-table">
        <thead>
            <tr>
                <th width="15%" class="head0">Date</th>
                <th width="50%" class="head1">Title</th>
                <th width="15%" class="head0">Location</th>
                <th width="10%" class="head1">Action</th>
            </tr>
        </thead>
    </table>
</div>

<style type="text/css">
    .aphabetical_filters{
        margin:0 0 0 10px;
    }
    a.letter_filter{
    }
    .dataTables_processing {
        position: absolute;
        top: 15px;
        left: 50%;
        width: 100px;
        margin-left: -125px;
        background-color: #E30;
        text-align: center;
        color: #FFF;
        padding: 2px 0;
        -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;
    }

    #events-data-table { border-collapse: collapse; }
    #events-data-table tr td { padding: 8px 10px; border-right: 1px solid #fff; border-bottom: 1px solid #ddd; vertical-align: top;}
    #events-data-table thead th { padding: 8px 10px; color: #ccc; text-shadow: 1px 1px #444; font-size: 12px; text-transform: uppercase; border-right: 1px solid #777; }
    #events-data-table thead th { font-weight: normal; text-align: left; }
    #events-data-table tr td:last-child { border-right: 0; }
    #events-data-table tr:last-child td { border-bottom: 0;}
    #events-data-table tr:hover { background: #cacaca; }
    #events-data-table tr.selected { background: #fffccc; }
/*    #events-data-table .head0 { background-color: #A79269; }
    #events-data-table .head1 { background-color: #77623d; }*/
    #events-data-table .odd { background-color: #eaeaea; }
    #events-data-table .even { background-color: #ddd; }
    div.jGrowl.top-right {
        right: 				0px;
        top: 				100px;
    }
    div.jGrowl div.jGrowl-notification{
        color:#000000;
        background:#A79269 ;
    }

</style>

<script type="text/javascript">
    /** Datatable code **/
    var oTable;
    var page = 'upcoming';
    $(window).bind('load',function(){
        $("#page_select").find("a").click(function(){
            page = ($(this).attr('rel'));
            $("#all").removeClass("current")
            $("#upcoming").removeClass("current")
            $("#past").removeClass("current")
            $("#"+page).addClass("current")
            oTable.fnDestroy();
            init_oTable_initialize(page);
            $("#events-data-table").css("width","100%");
        });
        init_oTable_initialize(page);
        init_server_search_fix();   // Will search only hitting enter not keypress
        init_vendor_link();
    });

    function init_oTable_initialize(page){
        oTable=$('#events-data-table').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "iDisplayLength": 25,
            "sPaginationType": "full_numbers",
            "sAjaxSource": site_url+'/client/event/ajax-Get-Events-Dt/page/'+page,
            "sServerMethod": "POST",
            "oLanguage": {
                "sSearch": "Search Events by Title:"
            },
            "aaSorting": [[0,'asc']], // Initial sorting order when page loads
            "aoColumnDefs":[{ "bSortable": true, "aTargets": [ 0 ] },{ "bSortable": true, "aTargets": [ 1 ] },{ "bSortable": true, "aTargets": [ 2 ] }, { "bSortable": false, "aTargets": [ 3 ] }],   // Turning sorting on/off for cols
            "fnInitComplete": function (oSettings, json) {
                //*$('#'+oSettings.sInstance+'_wrapper').find('.dataTables_length label:eq(0)').after($('.aphabetical_filters'));
            }
        } );
    }

    function init_vendor_link(){
        $(document).on("click", ".view", function(){            
            var link = site_url+"/client/event/event-Details/id/"+$(this).attr('rel');
            loadDetailsView(link);
        });
    }

    function init_server_search_fix(){
        $('.dataTables_filter input').unbind('keypress keyup').bind('keypress', function(e){
            if (e.which == 13){
                oTable.fnFilter($(this).val(), null, false, true);
                //oTable.fnDraw();
                return;
            }
        });
    }

    function init_alphabetical_filters(){
        $('.letter_filter').on('click',function(){
            oTable.fnFilter($(this).text());
        });
    }
    /** Datatable code **/
</script>

<script type="text/javascript">

    function loadDetailsView(thisItem){
        $.fancybox({
            'width'                 : 800,
            'height'                : '80%',
            'href'                  : thisItem,
            'autoScale'             : true,
            'overlayColor'          : '#FFF',
            'type'                  : 'iframe',
            'speedIn'               : 100,
            'speedOut'              : 100,
            'overlayShow'	      : true,
            'onClosed'             : function() {
                // window.location = $obj.attr('param');
            }
        });
    }
</script>



